### ISSUE TITLE
Competing Consumers snapshotting broken

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#771] opened 2015-12-04 21:04 UTC
Repro:

 1. Start eventstore with system projections running
 2. Run a service with code as such (listing 1). Let the subscription crash so that the TODO is printed.
 3. Let EventStore fire another event which should come to the "my-group" subscription. E.g. an event in the stream "mypub-1234567"
 4. Observe that no event is pushed to the subscriber.
 5. Restart the subscriber. Still, no event is received.
 6. Recompile and change "my-group" to "my-group-tryagain" and remove the exception that is thrown  from the subscriber.
 7. Observe events starting to flow properly again.
 8. Restart the service.
 9. Push a new event
 10. Nothing happens.
 11. Goto 6.

Expected outcome, at step 4, events should be pushed to the subscriber.

Listing 1:

``` fsharp
let pss = PersistentSubscriptionSettings
      .Create()
      .StartFromBeginning()
      .ResolveLinkTos()
      .CheckPointAfter(TimeSpan(0,0,10))
      .MinimumCheckPointCountOf(1)
      .MaximumCheckPointCountOf(1)
      .Build()
Conn.createPersistent "$ce-mypub" "my-group" pss
Conn.connectPersistent "$ce-mypub"
                                 "my-group"
                                 (Subscription.myEventHandler)
                                 (Some (fun sub reason ex ->
                                   LogLine.error "TODO: handle events " |> LogLine.setData "exn" ex |> Logger.log logger))
                                 1u
                                 true
                                 conn
```

PS: this has nothing to do with us using F# - it's directly bound to your latest published event store API, so rewriting this in C# doesn't help. Also I believe I have given you enough information to avoid me having to write a C# test. You are welcome to write a C# test for this given the above information.

More information, how it looks in ES Web:

<img width="946" alt="screen shot 2015-12-04 at 22 08 02" src="https://cloud.githubusercontent.com/assets/193115/11601468/b33d88f4-9ad3-11e5-9c41-93b9c90ca478.png">

These are all the same consumer group that has been renamed due to:

Furthermore, deleting the consumer group doesn't help as there seems to be a snapshot stream that keeps track of how far the consumers have consumed into the stream, which means that our software won't re-read the stream even if I have to re-create the consumer group. The assumption I had there was that when I deleted a consumer group I also deleted its metadata, thereby allowing me to re-use the name, instead of having to add suffixes on every re-compile or restart of the service.

Environment:

Ubuntu 14.04 LTS, 64bit. Official binaries v3.3.0.

**Comment by gregoryyoung** [comment] 2015-12-04 22:03
I can reproduce the recreating part (a checkpoint stream remains) this will be resolved. To resolve yourself for now just delete the stream: $persistentsubscription-{sub}-checkpoint


For the initial thing you should be seeing a subscription drop callback due to the exception. 
https://github.com/EventStore/EventStore/blob/release-v3.4.0/src/EventStore.ClientAPI/EventStorePersistentSubscriptionBase.cs#L199

**Comment by gregoryyoung** [comment] 2015-12-15 13:00
@haf looking back through the stream for the checkpoint is being deleted.

Have you changed security settings etc? https://github.com/EventStore/EventStore/blob/release-v3.4.0/src/EventStore.Core/Services/PersistentSubscription/PersistentSubscription.cs#L531 that might cause this to fail?

**Comment by haf** [comment] 2015-12-15 13:04
Afraid I haven't changed any security settings... We're using 3.3.0 though, not 3.4. It's reproducible in dev, too, right @mavnn @lapponiandevil?

**Comment by gregoryyoung** [comment] 2015-12-15 13:08
which is? the first part of your problem is expected behaviour an unhanded exception in user code causes the subscription to drop (the error handler is empty). The second part is the recreation of stream with same name. I don't see any relevant code since 3.3 and 3.4 seems not recreatable. When you delete the stream is the checkpoint stream deleted? its "$persistentsubscription-{sub name}-checkpoint"

**Comment by haf** [comment] 2015-12-15 13:10
It would seem the checkpoint stream is not deleted, otherwise the consumption of the group would resume, right?

**Comment by pgermishuys** [comment] 2015-12-15 13:17
@haf would you mind confirming that the checkpoint stream is deleted by doing a curl and verifying that you received a 404?
`curl -i "http://localhost:2113/streams/%24persistentsubscription-%24ce-mypub::my-group-checkpoint" -H "accept:application/json" -u admin:changeit` ?

**Comment by gregoryyoung** [comment] 2015-12-15 13:23
@haf I am referring to the inability to recreate a stream. It seems the checkpoint stream is being deleted on a delete operation.

For the subscription stopping this appears to be expected behaviour (it should call back the error handler in the case of an unhanded exception in the handler) you would need to resubscribe at this point (unless I am misunderstanding what you are saying) https://github.com/EventStore/EventStore/blob/release-v3.4.0/src/EventStore.ClientAPI/EventStorePersistentSubscriptionBase.cs#L202

**Comment by haf** [comment] 2015-12-15 13:29
The issue is that the resubscribe doesn't give you any messages.

**Comment by lapponiandevil** [comment] 2015-12-15 13:40
@pgermishuys, @gregoryyoung The checkpoint streams are still there.

**Comment by gregoryyoung** [comment] 2015-12-15 13:47
Where are you deleting the subscription in between? on the "recreate"?

**Comment by lapponiandevil** [comment] 2015-12-15 13:50
Just to clarify,
We are not hoping to delete a subscription, because that would mean we would have to start from the beginning again, right?

If/when a subscribing service goes down, we want to resume the subscription at the checkpoint when resubscribing. After doing just that and pushing new events to the stream, nothing happens for the new subscriber.
To get hold of the latest events, we have had to create a new group, which subscribes to the same stream. In that fashion we also get all old events, which is not what we want.

**Comment by gregoryyoung** [comment] 2015-12-15 14:01
I am just curious how long you are waiting in between?

By default there is a buffer size of 500 messages and a timeout of 30
seconds. Is it possible that all of your messages are buffered and awaiting
timeout?

On Tue, Dec 15, 2015 at 1:50 PM, Mikko Lappalainen <notifications@github.com
> wrote:

> Just to clarify,
> We are not hoping to delete a subscription, because that would mean we
> would have to start from the beginning again, right?
>
> If/when a subscribing service goes down, we want to resume the
> subscription at the checkpoint when resubscribing. After doing just that
> and pushing new events to the stream, nothing happens for the new
> subscriber.
> To get hold of the latest events, we have had to create a new group, which
> subscribes to the same stream. In that fashion we also get all old events,
> which is not what we want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/771#issuecomment-164770089>
> .
>



-- 
Studying for the Turing test

**Comment by lapponiandevil** [comment] 2015-12-15 14:06
We have waited way longer than 30 sec.

**Comment by gregoryyoung** [comment] 2015-12-15 14:18
I was figuring that on your second run you were removing the "create"

I am curious what are you doing to handle the error you will get the second time running? (If you create a subscription twice you should get an error).

**Comment by haf** [comment] 2015-12-15 14:27
Generally we fix the error; normally an integration that has changed API without telling us, recompile and redeploy. Hence we'd like it to resume from there.

**Comment by gregoryyoung** [comment] 2015-12-15 14:28
"Generally we fix the error; normally an integration that has changed API without telling us, recompile and redeploy. Hence we'd like it to resume from there."

In your code above you will get an error on the second run when creating the subscription as it already exists. Do you just ignore this error or?

**Comment by haf** [comment] 2015-12-15 14:29
``` fsharp

  EsAction.run esConn Conn.connect
  |> Job.bind (fun () ->
      let sub = subscribe esCreds (AccessToken.ensureApiConfigured kvconfig) (makeLoader s3Config)
      job {
        try
          let! _ = EsAction.run esConn sub
          return ()
        with
        | :? AggregateException as ae ->
          match ae.Flatten().InnerExceptions.[0] with
          | :? InvalidOperationException as ioe
              when ioe.Message.Contains("on stream $ce-voucherpubs already exists") ->
            return ()
          | innermost ->
            printfn "Innermost: %s,\n%A" (innermost.GetType().Name) innermost
            return raise innermost
        | other ->
          printfn "Other: %s,\n%A" (other.GetType().Name) other
          return ()
      })
  |> run
  |> ignore
```

Yes, we ignore it.

**Comment by haf** [comment] 2015-12-15 14:41
Not recreating that continuously is a good avenue to go down, let me get back. It may be that just talking about it with you guys has helped a lot!

**Comment by gregoryyoung** [comment] 2015-12-15 14:43
I am curious if the behavior exists when not being created every time. The
rest of the code appears to be almost exactly what I used in my sand box
when running.

On Tue, Dec 15, 2015 at 2:41 PM, Henrik Feldt <notifications@github.com>
wrote:

> Not recreating that continuously is a good avenue to go down, let me get
> back. It may be that just talking about it with you guys has helped a lot!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/771#issuecomment-164783701>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment] 2015-12-15 15:33
What am I missing in my code in trying to reproduce this issue?

    class Program

    {

        private static string group = "foo";

        private static string stream = "bar";


        static void Main(string[] args)

        {

            using (var c = EventStoreConnection.Create(new IPEndPoint(
IPAddress.Loopback, 1113)))

            {

                c.ConnectAsync().Wait();

                //CreateCompetingGroup(c);

                c.ConnectToPersistentSubscription(stream, @group,

                (sender,e) =>

                {

                    //resolved event

                    Console.WriteLine("Received " + e.OriginalEventNumber);

                },

                (sender, reason, exc) =>

                {

                    Console.WriteLine("error " + reason);

                });

                Thread.Sleep(500);

                for (var i = 0; i < 20; i++)

                {

                    c.AppendToStreamAsync(stream, ExpectedVersion.Any,

                        new EventData(Guid.NewGuid(), "foo", false,
new byte[100],
new byte[100])).Wait();

                }

                Thread.Sleep(5000);

            }

        }


        private static void CreateCompetingGroup(IEventStoreConnection
eventStoreConnection)

        {

            eventStoreConnection.CreatePersistentSubscriptionAsync(stream,
@group, PersistentSubscriptionSettings
.Create().ResolveLinkTos().StartFromBeginning(),

                new UserCredentials("admin", "changeit")).Wait();

        }

On Tue, Dec 15, 2015 at 2:43 PM, Greg Young <gregoryyoung1@gmail.com> wrote:

> I am curious if the behavior exists when not being created every time. The
> rest of the code appears to be almost exactly what I used in my sand box
> when running.
>
> On Tue, Dec 15, 2015 at 2:41 PM, Henrik Feldt <notifications@github.com>
> wrote:
>
>> Not recreating that continuously is a good avenue to go down, let me get
>> back. It may be that just talking about it with you guys has helped a lot!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/771#issuecomment-164783701>
>> .
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by lapponiandevil** [comment] 2015-12-15 19:11
@gregoryyoung It looks about right to me, except for "CreateCompetingGroup", that you have commented out, where we had a handler for the expected error.
Simply put, there was an error in our error-handling of the double creation of a subscription.

Thank you for the questions and support!
This issue can be closed.

**Comment by pgermishuys** [comment] 2015-12-15 19:18
Closing this issue, thanks @lapponiandevil

**Closed by pgermishuys** 2015-12-15 19:18 UTC

**Comment by gregoryyoung** [comment] 2015-12-17 18:55
@haf ah yes I only ran that the first time then commented it out on subsequent runs.

**Comment by haf** [comment] 2015-12-18 11:35
Thanks for your help in solving this :+1:
