### ISSUE TITLE
EventStore 5 runs as split brain when ClusterDns is not available

### ISSUE THREAD

**Issue by dnagir** [EventStore/EventStore#1878] opened 2019-03-01 03:19 UTC
Hello,

When provisioning a new cluster configured to use `ClusterDns`, the nodes just elect themselves as leaders while being completely unaware they are in a cluster despite being configured with `ClusaterDns` + `DiscoverViaDns: True`.

### Logs

```
{ "PID": "2272", "ThreadID": "1", "Date": "2019-03-01T01:56:43.826056Z", "Level": "Info", "Logger": "ProgramBase`1", "Message": "Quorum size set to {quorum}", "EventProperties": { "quorum": 1 } }
```

and later

```
{ "PID": "2272", "ThreadID": "13", "Date": "2019-03-01T01:56:44.285518Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: STARTING ELECTIONS.", "EventProperties": {  } }
{ "PID": "2272", "ThreadID": "13", "Date": "2019-03-01T01:56:44.285518Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) SHIFT TO LEADER ELECTION.", "EventProperties": { "view": 0 } }
{ "PID": "2272", "ThreadID": "13", "Date": "2019-03-01T01:56:44.285518Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) VIEWCHANGE FROM [{serverInternalHttp}, {serverId:B}].", "EventProperties": { "view": 0, "serverInternalHttp": "172.31.16.11:2112", "serverId": "8cd1cd66-2385-4f04-a82a-f4f0aad415d8" } }
{ "PID": "2272", "ThreadID": "13", "Date": "2019-03-01T01:56:44.290322Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) MAJORITY OF VIEWCHANGE.", "EventProperties": { "view": 0 } }
{ "PID": "2272", "ThreadID": "13", "Date": "2019-03-01T01:56:44.290322Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={lastAttemptedView}) SHIFT TO PREPARE PHASE.", "EventProperties": { "lastAttemptedView": 0 } }
{ "PID": "2272", "ThreadID": "13", "Date": "2019-03-01T01:56:44.290322Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) PREPARE_OK FROM {nodeInfo}.", "EventProperties": { "view": 0, "nodeInfo": "[172.31.16.11:2112,{8cd1cd66-2385-4f04-a82a-f4f0aad415d8}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000})" } }
{ "PID": "2272", "ThreadID": "13", "Date": "2019-03-01T01:56:44.295667Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={lastAttemptedView}) SHIFT TO REG_LEADER.", "EventProperties": { "lastAttemptedView": 0 } }
{ "PID": "2272", "ThreadID": "13", "Date": "2019-03-01T01:56:44.304163Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={lastAttemptedView}) SENDING PROPOSAL CANDIDATE: {formatNodeInfo}, ME: {ownInfo}.", "EventProperties": { "lastAttemptedView": 0, "formatNodeInfo": "[172.31.16.11:2112,{8cd1cd66-2385-4f04-a82a-f4f0aad415d8}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000})", "ownInfo": "[172.31.16.11:2112,{8cd1cd66-2385-4f04-a82a-f4f0aad415d8}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000})" } }
{ "PID": "2272", "ThreadID": "13", "Date": "2019-03-01T01:56:44.305175Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) ACCEPT FROM [{serverInternalHttp},{serverId:B}] M=[{masterInternalHttp},{masterId:B}]).", "EventProperties": { "view": 0, "serverInternalHttp": "172.31.16.11:2112", "serverId": "8cd1cd66-2385-4f04-a82a-f4f0aad415d8", "masterInternalHttp": "172.31.16.11:2112", "masterId": "8cd1cd66-2385-4f04-a82a-f4f0aad415d8" } }
{ "PID": "2272", "ThreadID": "13", "Date": "2019-03-01T01:56:44.305175Z", "Level": "Info", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) DONE. ELECTED MASTER = {masterInfo}. ME={ownInfo}.", "EventProperties": { "view": 0, "masterInfo": "[172.31.16.11:2112,{8cd1cd66-2385-4f04-a82a-f4f0aad415d8}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000})", "ownInfo": "[172.31.16.11:2112,{8cd1cd66-2385-4f04-a82a-f4f0aad415d8}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000})" } }
```

## Config

```yaml
Log: /mnt/eventstore/logs
Db: /mnt/eventstore/db
Index: /mnt/eventstore/db/index
SkipDbVerify: True # Default - False. Do not verify it slows down the startup

StartStandardProjections: False # Enable built-in (system) projection
StatsPeriodSec: 60 # seconds - stats stream - increase to make it less noisy (def - 30)
WorkerThreads: 5 # for pool of worker services
RunProjections: None

ClusterDns: the-dns-that-was-not-resolvable.example.com
DiscoverViaDns: True
ClusterGossipPort: 2112 # default - assumes a manager node
IntIp: 172.31.16.11
ExtIp: 172.31.16.11
IntHttpPrefixes: http://*:2112/
ExtHttpPrefixes: http://*:2113/
AddInterfacePrefixes: False
```

## Workaround

Fixing the cluster size with `ClusterSize: 3` makes the nodes fail correctly with the logs:

```
{ "PID": "2981", "ThreadID": "14", "Date": "2019-03-01T02:57:21.064837Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) TIMED OUT! (S={state}, M={master}).", "EventProperties": { "view": 632, "state": "ElectingLeader", "master": null } }
{ "PID": "2981", "ThreadID": "14", "Date": "2019-03-01T02:57:21.064837Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) SHIFT TO LEADER ELECTION.", "EventProperties": { "view": 633 } }
{ "PID": "2981", "ThreadID": "14", "Date": "2019-03-01T02:57:21.064837Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) VIEWCHANGE FROM [{serverInternalHttp}, {serverId:B}].", "EventProperties": { "view": 633, "serverInternalHttp": "172.31.16.11:2112", "serverId": "9b07b924-f2c2-40c7-ae0f-dc5aa833c1f2" } }
{ "PID": "2981", "ThreadID": "10", "Date": "2019-03-01T02:57:21.868006Z", "Level": "Error", "Logger": "GossipServiceBase", "Message": "Error while retrieving cluster members through DNS.", "Exception": {"ErrorCode":11001, "Message":"Could not resolve host 'the-dns-that-was-not-resolvable.example.com'", "SocketErrorCode":"HostNotFound", "NativeErrorCode":11001, "Data":{}, "StackTrace":"  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_delegate_end_invoke(object,intptr)\n  at (wrapper delegate-end-invoke) <Module>.end_invoke_IPAddress[]__this___IAsyncResult(System.IAsyncResult)\n  at System.Net.Dns.EndGetHostAddresses (System.IAsyncResult asyncResult) [0x00038] in <c0e40d34c25e4827874530676d4126b9>:0 \n  at EventStore.Core.Services.Gossip.DnsGossipSeedSource.EndGetHostEndpoints (System.IAsyncResult asyncResult) [0x00000] in <a6dbc0b66b5d4a248e617efa39a5eaed>:0 \n  at EventStore.Core.Services.Gossip.GossipServiceBase.OnGotGossipSeedSources (System.IAsyncResult ar) [0x00000] in <a6dbc0b66b5d4a248e617efa39a5eaed>:0 ", "HResult":-2147467259}, "EventProperties": {  } }
{ "PID": "2981", "ThreadID": "14", "Date": "2019-03-01T02:57:22.067895Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) TIMED OUT! (S={state}, M={master}).", "EventProperties": { "view": 633, "state": "ElectingLeader", "master": null } }
{ "PID": "2981", "ThreadID": "14", "Date": "2019-03-01T02:57:22.073335Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) SHIFT TO LEADER ELECTION.", "EventProperties": { "view": 634 } }
{ "PID": "2981", "ThreadID": "14", "Date": "2019-03-01T02:57:22.073335Z", "Level": "Debug", "Logger": "ElectionsService", "Message": "ELECTIONS: (V={view}) VIEWCHANGE FROM [{serverInternalHttp}, {serverId:B}].", "EventProperties": { "view": 634, "serverInternalHttp": "172.31.16.11:2112", "serverId": "9b07b924-f2c2-40c7-ae0f-dc5aa833c1f2" } }
```

**Comment by gregoryyoung** [comment] 2019-03-01 03:50
Its not "split brain" really... you have said they are independent nodes via config (clusterSize: 1). If clusterSize was 3 then they would loop on the dns I believe.

This should probably give an error "Hey you have told me I am both a cluster node and not a cluster node" :+1:?

Does that seem reasonable to you?

**Comment by jen20** [comment] 2019-03-01 04:27
This seems like a reasonable startup warning to add.

**Comment by dnagir** [comment] 2019-03-01 04:46
Yeah, a warning (or better a failure would definitely be helpful and "safer").

I am not sure I'm understanding why the fixed `ClusterSize` needs to be set when the `ClusterDns` is the source of truth of the nodes. `ClusterDns` should take precedence.
But a way of "removing" the `ClusterSize` would be reasonable (so that it is no longer `1` - undefined).

It would make it very hard to scale in and out the cluster (all of the nodes need to get the updated config be restarted).

**Comment by gregoryyoung** [comment] 2019-03-01 20:06
"I am not sure I'm understanding why the fixed `ClusterSize` needs to be set when the `ClusterDns` is the source of truth for all the nodes".

Clusterdns is not a source of truth for all nodes. Dns would also make a terrible source of truth (can be poisoned easily etc). ClusterDns just finds the ip addresses of some other nodes, it is a mechanism of discovery (a hint). When a node comes up unless its a single node it needs to talk to (discover) other nodes to figure out what is going on, what needs to be done, and what role it may play. In many environments you may not know the ip addresses of the other nodes to start with (with immutable infrastructure/cloud deployments as example the ip addresses of nodes can change... the nodes don't have fixed ips). 

There are a few other ways of finding the other nodes (list of ip addresses to try gossiping with from command line as example but what are those initial ips and how does this get changed every time a new node comes in with a different ip?). ClusterDns is another such mechanism, it says to use a dns lookup to get back that initial list of ip addresses to check for nodes to try to gossip with, this is useful in the case mentioned as nodes can register themselves with the dns on load (aka advertisement). No additional tools are needed in ES to accomplish this. This is especially useful when doing things like immutable infrastructure as new node can discover via dns and can advertise its existence through dns. This same process also happens in the client when it tries to discover the cluster via dns... dns is a "hint" as to where it might find the nodes to get more information from, if clients were hardcoded with ips they would need restarts on some changes (imagine releasing a new version in the cloud and all the ip addresses change).

There has been talk in the past about offering another discovery mechanism via say udp broadcast etc but there are many places where it can't work (especially the cloud! udp packets not routed etc).

Does this clarify things a bit?

**Comment by dnagir** [comment] 2019-03-04 08:55
Thanks @gregoryyoung - that makes sense.

How would you suggest (auto)scaleing the cluster in and out without fixing a `ClusterSize` while using `ClusterDns` for discovery?

The use case is that we want to run a smaller number of instances when there is less load and larger when there is more.

**Comment by gregoryyoung** [comment] 2019-03-05 04:34
"How would you suggest (auto)scaling the cluster in and out without fixing a ClusterSize while using ClusterDns for discovery?"

This is for read load? Scaling out nodes won't help write load (it actually requires more acks as it is consistent)

For read load the big question is what level of assurance do you need?
Where are you currently hitting bottlenecks?

**Comment by dnagir** [comment] 2019-03-06 23:50
The main purpose at this stage is to try to save cost due to the spiky nature of the load:

- most writes - during work hours, peaking about 2-3 times a day
- little write load outside of the work hours, including weekends (only internal services)
- most read load would be matching the write load
- spiky read load for replays (during work hours and outside) due to us getting things wrong and rebuilding projections


What we had in mind was:
- run large instances in multiple availability zones (so need at least 3)
- dedicate one node to backups
- scale the cluster out to 5, 7 by adding smaller instances (off-peak)
- stop the larger instances (off-peak)
- reverse the above for peak hours

For that, it would be ideal if we didn't have to fix the `ClusterSize` as we definitely want to have some options around scaling in and out.

What would you suggest knowing the above?

**Comment by gregoryyoung** [comment] 2019-03-07 20:41
If you are not trying to scale for write purposes but for read would the ability to just drop in nodes that have the data but do not participate in write consensus solve what you are looking for?

**Comment by dnagir** [comment] 2019-03-15 00:43
> If you are not trying to scale for write purposes but for read would the ability to just drop in nodes that have the data but do not participate in write consensus solve what you are looking for?

That could do the job (but I'm not sure how to configure the node to not participate in the consensus).

But wouldn't that still require `ClusterSize` not to be fixed?

**Comment by gibletto** [comment] 2019-04-12 15:04
You can add nodes without changing ClusterSize, they just will become either Clones or Non-Promotable Clones depending on your setup.

**Comment by ylorph** [comment] 2022-10-26 08:20
Closing , this is working as intended

**Closed by ylorph** 2022-10-26 08:20 UTC
Labels: kind/enhancement, impact/medium, detectability/unknown
