### ISSUE TITLE
Port to Core

### ISSUE THREAD

**Issue by evilpilaf** [EventStore/EventStore#831] opened 2016-03-03 23:25 UTC

**Comment by gregoryyoung** [comment] 2016-03-03 23:49
port what to core the backend? core is far from stable to move the backend to at this point.

**Comment by gregoryyoung** [comment] 2016-03-03 23:54
we know this as @jageall spent over a week working on it.

**Comment by evilpilaf** [comment] 2016-03-04 16:10
Yeah, I know it's still in the early stages, but a server port to core would bring many benefits like really easy deployment across platforms and OS, and also to Docker, so we could publish event store databases to azure container service or servicefabric in an easy way

**Comment by gregoryyoung** [comment] 2016-03-04 17:56
Most of what you suggested is already supported via mono except it already
has packages etc.

Core is at this point not ready to run in production. As it moves forward
we will re-evaluate.

On Fri, Mar 4, 2016 at 6:10 PM, evilpilaf <notifications@github.com> wrote:

> Yeah, I know it's still in the early stages, but a server port to core
> would bring many benefits like really easy deployment across platforms and
> OS, and also to Docker, so we could publish event store databases to azure
> container service or servicefabric in an easy way
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/831#issuecomment-192337389>
> .
>



-- 
Studying for the Turing test

**Comment by evilpilaf** [comment] 2016-03-04 19:45
Ok, sounds great, will look into packing it into a docker image, thanks :)

**Comment by gregoryyoung** [comment] 2016-03-05 13:29
A docker image should be pretty easy to setup (just install the apt-get
package).

On Fri, Mar 4, 2016 at 9:45 PM, evilpilaf <notifications@github.com> wrote:

> Ok, sounds great, will look into packing it into a docker image, thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/831#issuecomment-192435773>
> .
>



-- 
Studying for the Turing test

**Comment by javinovo** [comment] 2016-07-11 09:36
Has this been re-evaluated since version 1 was released?
For instnace, we intended to use it in an ASP.NET Core REST service.

**Comment by javinovo** [comment] 2016-07-11 09:41
Has this been re-evaluated since version 1 was released?
Particularly, we are interested in the .NET Client, since we intended to use it in an ASP.NET Core REST service.

**Comment by gregoryyoung** [comment] 2016-07-11 09:54
there is a branch where this work is being done. the client will likely be
supported but not the backend at this point.

On Mon, Jul 11, 2016 at 12:41 PM, javinovo <notifications@github.com> wrote:

> Has this been re-evaluated since version 1 was released?
> Particularly, we are interested in the .NET Client, since we intended to
> use it in an ASP.NET Core REST service.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/EventStore/EventStore/issues/831#issuecomment-231688063>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXRWlYtjsTbWTUngXuTmvLbRup5UuLJks5qUg_LgaJpZM4Ho74k>
> .
>



-- 
Studying for the Turing test

**Comment by eric-swann-q2** [comment] 2016-07-15 18:47
FYI, [this fork](https://github.com/qooroo/EventStore/tree/dotnet-core) has been ported and is used [in this project](https://github.com/AdaptiveConsulting/ReactiveTraderCloud) so I gather it is working.

**Comment by stefc** [comment] 2016-08-01 08:02
Did somebody know if that mentioned fork have some nuget package somewhere ?

**Comment by pgermishuys** [comment] 2016-08-01 09:10
This seems to be a duplicate of the client core port. Going to close this in favour of https://github.com/EventStore/EventStore/issues/757.

**Closed by pgermishuys** 2016-08-01 09:10 UTC
Labels: question
