### ISSUE TITLE
Prevent any writes to streams owned by Projections.

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#2049] opened 2019-11-11 14:21 UTC
Projections needs to prevent any other clients apart from itself to write messages to the streams it owns.
As it currently stands, Event Store allows it and then fails when it restarts after having detected that a write was made to the stream where the expected version didn't match.
e.g.
```
[19512,19,14:19:20.256] Failed to write events to stream "$et-foo-eventType". Error: "WrongExpectedVersion"
[19512,19,14:19:20.256] Projection '"$by_event_type"'(41c4ced3-209b-4130-86dc-c1d367324d3c) restart has been requested due to: '"The '$et-foo-eventType' stream has been written to from the outside. Expected Version: 0, Current Version: 1. Checkpoint: C:0/P:
-1."'
[19512,19,14:19:20.256] PROJECTIONS: Scheduling the writing of "$started" to "$projections-$master". Current status of Writer: Busy: true
[19512,17,14:19:20.256] PROJECTIONS: Response received: 87@"$started"
[19512,19,14:19:20.256] PROJECTIONS: Finished writing events to "$projections-$master": "$started"
[19512,19,14:19:20.301] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler '"Projection Core #1"'.
EXCEPTION OCCURRED
The given checkpoint is invalid. Possible causes might include having written an event to the projection's managed stream. The bad checkpoint: Phase: 0
[19512,19,14:19:20.337] Global Unhandled Exception occurred.
EXCEPTION OCCURRED
The given checkpoint is invalid. Possible causes might include having written an event to the projection's managed stream. The bad checkpoint: Phase: 0

```

**Comment by zhuzhenguang** [comment] 2020-05-29 11:18
Hi
I also encounter this issue, and how should I fix it? Now the $by_category projection faulted: The given checkpoint is invalid. Possible causes might include having written an event to the projection's managed stream. The bad checkpoint: Phase: 0

**Comment by blocka** [comment] 2020-06-17 06:03
I also encountered this. How can we fix it? I believe I know what stream it was, so would it work to delete it, and then restart the projection?

**Comment by blocka** [comment] 2020-06-17 06:05
I also tried to reproduce the issue on a local instance. I wrote to stream that was created by the $by_event_type projection, but this error didn't happen.

**Comment by TAGC** [comment] 2021-02-03 15:37
This has just caused MASSIVE ISSUES for us in production. How the hell was this ever allowed in the the first place?

**Comment by alexeyzimarev** [comment] 2021-02-03 16:16
@TAGC I would suggest opening a support ticket for urgent production issues.

**Comment by oskardudycz** [comment] 2022-01-28 09:49
Closing it as a duplicate of https://github.com/EventStore/EventStore/issues/3149.

**Closed by oskardudycz** 2022-01-28 09:49 UTC
Labels: kind/enhancement, subsystem/projections
