### ISSUE TITLE
How to setup HTTPS?

### ISSUE THREAD

**Issue by memark** [EventStore/EventStore#802] opened 2016-02-08 16:03 UTC
I have successfully enabled SSL for the TCP connections. But how is it done for the HTTP (admin) interface? It feels equally (if not more) important. Is there any documentation on this?

**Comment by gregoryyoung** [comment] 2016-02-08 22:50
which environment?

On Mon, Feb 8, 2016 at 6:05 PM, Magnus Markling <notifications@github.com>
wrote:

> I have successfully enabled SSL for the TCP connections. But how is it
> done for the HTTP (admin) interface? It feels equally (if not more)
> important. Is there any documentation on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/802>.
>



-- 
Studying for the Turing test

**Comment by memark** [comment] 2016-02-08 22:57
Both Windows and Ubuntu actually.

**Comment by gregoryyoung** [comment] 2016-02-09 08:25
Its just a http listener so its the same for anything that uses http
listener these might be out of date but will make an issue to check them

https://github.com/EventStore/EventStore/wiki/Setting-Up-SSL-In-Windows
https://github.com/EventStore/EventStore/wiki/Setting-Up-SSL-In-Linux

Cheers,

Greg

On Mon, Feb 8, 2016 at 10:57 PM, Magnus Markling <notifications@github.com>
wrote:

> Both Windows and Ubuntu actually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/802#issuecomment-181610159>
> .
>



-- 
Studying for the Turing test

**Comment by memark** [comment] 2016-02-11 13:11
Thanks, Greg. I'm able to configure the SSL cert for the listener. But that doesn't seem to be enough. Is there no need for any change in EventStore config? (The page mentions nothing about this.) Trying to reach the HTTP interface on windows now gives me _ERR_SSL_PROTOCOL_ERROR_ in Chrome.

**Comment by gregoryyoung** [comment] 2016-02-11 20:01
No mention of which os but the whole point of the abstraction is outside
config.

On Thursday, February 11, 2016, Magnus Markling <notifications@github.com>
wrote:

> Thanks, Greg. I'm able to configure the SSL cert for the listener. But
> that doesn't seem to be enough. Is there no need for any change in not of
> the EventStore config? (The page mentions nothing about this.) Trying to
> reach the HTTP interface on windows now gives me *ERR_SSL_PROTOCOL_ERROR*
> in Chrome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/802#issuecomment-182857839>
> .
>


-- 
Studying for the Turing test

**Comment by AlessandroEmm** [comment] 2016-02-12 07:21
@gregoryyoung I'm also interested in this. But I'd prefer a solution with an external TLS Terminator such as stunnel or hitch. The only problem in that approach breaks the ATOM Protocol in the HTTP interface as there are http:// urls being generate. Can I configure this behavior somehow?

**Comment by AlessandroEmm** [comment] 2016-02-12 08:20
OK i just realized, it could be done by setting http headers. https://github.com/EventStore/EventStore/blob/98a95316bbb8f3f5cad2af835494b7edc2f492d9/src/EventStore.Transport.Http/EntityManagement/HttpEntity.cs#L29 
Thing is, to do that i would have to have a reverse proxy that interprets the whole http traffic - which is not something I'm really looking for in front of a DB ;-)

**Comment by memark** [comment] 2016-02-12 14:25
@gregoryyoung I mention at the end of my reply that I have been trying on Windows.

**Comment by pgermishuys** [comment] 2016-02-12 14:40
@memark there is no configuration needed from an Event Store point of view to get https working.
The steps described in https://github.com/EventStore/EventStore/wiki/Setting-Up-SSL-In-Windows should be good enough apart from the httpcfg and using `netsh http add sslcert ipport=0.0.0.0:port certhash=thumbprint appid={app_guid}`.

**Comment by memark** [comment] 2016-02-12 15:35
@pgermishuys Thx for confirming this. Then something else is wrong on my system. I currently get a standard HTTP response back on that port when trying to initiate the TLS handshake. Just to confirm, the basic idea is for Windows to step in, take care of the TLS channel, and then hand over clean HTTP requests to the registered listener (in this case EventStore)? (Working like a classic SSL terminator.)

**Comment by gregoryyoung** [comment] 2016-02-12 15:38
Yes this is handled via http.sys the request comes back to httplistener
either way though there are some flags set. The configuration side is of
http.sys not of eventstore. For TCP the configuration is of eventstore
(which is why you may see some possibly confusing arguments). The one thing
you do need to do IIRC is add a https://* prefix as well as the http://
prefixes

On Fri, Feb 12, 2016 at 3:35 PM, Magnus Markling <notifications@github.com>
wrote:

> @pgermishuys <https://github.com/pgermishuys> Thx for confirming this.
> Then something else is wrong on my system. I currently get a standard HTTP
> response back on that port when trying to initiate the TLS handshake. Just
> to confirm, the basic idea is for Windows to step in, take care of the TLS
> channel, and then hand over clean HTTP requests to the registered listener
> (in this case EventStore)? (Working like a classic SSL terminator.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/802#issuecomment-183376557>
> .
>



-- 
Studying for the Turing test

**Comment by memark** [comment] 2016-02-12 16:16
Thx, finally got it working! Here's a small outline of what needs to be done on windows to get it working:

1. install a TLS certificate
2. use _netsh_ to bind this certificate to an available port. this port needs to be **different** than the port configured with _--ext-http-port_
3. configure an additional http.sys prefix with _--ext-http-prefixes_ with the new port number

Both 2 and 3 were impossible for me to figure out by myself without prior knowledge of how _http.sys_ works or what constitutes a "prefix".

Example commands (using ports 2113 and 2114)
2. `netsh http add sslcert ipport=0.0.0.0:2114 certhash=... appid={...}`
3. `EventStore.ClusterNode.exe --ext-http-port=2113 --ext-http-prefixes="https://*:2114/"`

Tthis has taken a more than reasonable amount of my time this week to get working, so I would love   to help out updating/rewriting the documentation! (How do I go about doing that? I saw that you opened a ticket about a few days ago.)

**Comment by gregoryyoung** [comment] 2016-02-12 17:33
Just update the docs (they are a github repository). Under server just add
a doc "setting up https"

On Fri, Feb 12, 2016 at 4:16 PM, Magnus Markling <notifications@github.com>
wrote:

> Thx, finally got it working! Here's a small outline of what needs to be
> done on windows to get it working:
>
>    1. install a TLS certificate
>    2. use *netsh* to bind this certificate to an available port. this
>    port needs to be *different* than the port configured with
>    *--ext-http-port*
>    3. configure an additional http.sys prefix with *--ext-http-prefixes*
>    with the new port number
>
> Both 2 and 3 were impossible for me to figure out by myself without prior
> knowledge of how *http.sys* works or what constitutes a "prefix".
>
> Example commands (using ports 2113 and 2114)
> 2. netsh http add sslcert ipport=0.0.0.0:2114 certhash=... appid={...}
> 3. EventStore.ClusterNode.exe --ext-http-port=2113
> --ext-http-prefixes="https://*:2114/"
>
> Tthis has taken a more than reasonable amount of my time this week to get
> working, so I would love to help out updating/rewriting the documentation!
> (How do I go about doing that? I saw that you opened a ticket about a few
> days ago.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/802#issuecomment-183392570>
> .
>



-- 
Studying for the Turing test

**Comment by pgermishuys** [comment] 2016-03-03 08:08
@memark can we possibly close this issue now and open one on the docs repository? seems more appropriate that the issue is raised and handled there (https://github.com/EventStore/docs.geteventstore.com)

**Closed by pgermishuys** 2016-03-03 08:08 UTC

**Comment by memark** [comment] 2016-03-03 08:35
Sure thing, np. I think there already is one in fact.
