### ISSUE TITLE
Stream Browser Not Working in Admin UI

### ISSUE THREAD

**Issue by mandeep-rubicon** [EventStore/EventStore#2709] opened 2020-10-04 23:41 UTC
**Describe the bug**
When following instructions from the website eventstore.com for Version 20.6.1.0, the Admin UI is working fine on our local machine, but the stream browser is not working at all.

Getting 404 for the url https://localhost:2113/streams/$scavenges/head/1?embed=tryharder

**To Reproduce**
1.

EventStore.ClusterNode.exe --Config "eventstore.config" --run-projections=all --enable-external-tcp --int-ip=0.0.0.0 --ext-ip=0.0.0.0

**Expected behavior**
The Admin UI should show the Stream Browser

**Actual behavior**
Stream Browser is disabled as url is throwing 404

**Config/Logs/Screenshots**
2. Eventstore.config is
CertificateStoreLocation: CurrentUser
CertificateStoreName: My
CertificateThumbPrint: 3C63B227FE3DE00A9F02DF70D357DB299998E9C8
CertificateSubjectName: CN=eventstore.com
TrustedRootCertificatesPath: "./trusted-root-cert"

3. Log 
EventStore.ClusterNode.exe --Config "eventstore.config" --run-projections=all --enable-external-tcp --int-ip=0.0.0.0 --ext-ip=0.0.0.0
[36456, 1,15:17:15.716,INF]
"ES VERSION:"             "20.6.1.0" ("master"/"9ea108855", "Fri, 25 Sep 2020 14:24:19 +0200")
[36456, 1,15:17:15.721,INF] "OS:"                     Windows ("Microsoft Windows NT 6.2.9200.0")
[36456, 1,15:17:15.722,INF] "RUNTIME:"                ".NET 3.1.8" (64-bit)
[36456, 1,15:17:15.722,INF] "GC:"                     "3 GENERATIONS"
[36456, 1,15:17:15.722,INF] "LOGS:"                   "C:\\ProgramData\\chocolatey\\lib\\eventstore-oss\\tools\\EventStore-OSS-Windows-2019-v20.6.1\\logs"
[36456, 1,15:17:15.729,INF] MODIFIED OPTIONS:

        CONFIG:                   eventstore.config (Command Line)
        RUN PROJECTIONS:          all (Command Line)
        ENABLE EXTERNAL TCP:      true (Command Line)
        INT IP:                   0.0.0.0 (Command Line)
        EXT IP:                   0.0.0.0 (Command Line)
        CERTIFICATE STORE LOCATION: CurrentUser (Config File)
        CERTIFICATE STORE NAME:   My (Config File)
        CERTIFICATE THUMBPRINT:   3C63B227FE3DE00A9F02DF70D357DB299998E9C8 (Config File)
        CERTIFICATE SUBJECT NAME: CN=eventstore.com (Config File)
        TRUSTED ROOT CERTIFICATES PATH: ./trusted-root-cert (Config File)

DEFAULT OPTIONS:

        HELP:                     False (<DEFAULT>)
        VERSION:                  False (<DEFAULT>)
        LOG:                      C:\ProgramData\chocolatey\lib\eventstore-oss\tools\EventStore-OSS-Windows-2019-v20.6.1\logs (<DEFAULT>)
        LOG LEVEL:                Default (<DEFAULT>)
        WHAT IF:                  False (<DEFAULT>)
        START STANDARD PROJECTIONS: False (<DEFAULT>)
        DISABLE HTTP CACHING:     False (<DEFAULT>)
        HTTP PORT:                2113 (<DEFAULT>)
        INT TCP PORT:             1112 (<DEFAULT>)
        EXT TCP PORT:             1113 (<DEFAULT>)
        EXT HOST ADVERTISE AS:    <empty> (<DEFAULT>)
        ADVERTISE HOST TO CLIENT AS: <empty> (<DEFAULT>)
        ADVERTISE HTTP PORT TO CLIENT AS: 0 (<DEFAULT>)
        ADVERTISE TCP PORT TO CLIENT AS: 0 (<DEFAULT>)
        EXT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        HTTP PORT ADVERTISE AS:   0 (<DEFAULT>)
        INT HOST ADVERTISE AS:    <empty> (<DEFAULT>)
        INT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        INT TCP HEARTBEAT TIMEOUT: 700 (<DEFAULT>)
        EXT TCP HEARTBEAT TIMEOUT: 1000 (<DEFAULT>)
        INT TCP HEARTBEAT INTERVAL: 700 (<DEFAULT>)
        EXT TCP HEARTBEAT INTERVAL: 2000 (<DEFAULT>)
        GOSSIP ON SINGLE NODE:    False (<DEFAULT>)
        CONNECTION PENDING SEND BYTES THRESHOLD: 10485760 (<DEFAULT>)
        CONNECTION QUEUE SIZE THRESHOLD: 50000 (<DEFAULT>)
        CLUSTER SIZE:             1 (<DEFAULT>)
        NODE PRIORITY:            0 (<DEFAULT>)
        MIN FLUSH DELAY MS:       2 (<DEFAULT>)
        COMMIT COUNT:             -1 (<DEFAULT>)
        PREPARE COUNT:            -1 (<DEFAULT>)
        DISABLE ADMIN UI:         False (<DEFAULT>)
        DISABLE STATS ON HTTP:    False (<DEFAULT>)
        DISABLE GOSSIP ON HTTP:   False (<DEFAULT>)
        DISABLE SCAVENGE MERGING: False (<DEFAULT>)
        SCAVENGE HISTORY MAX AGE: 30 (<DEFAULT>)
        DISCOVER VIA DNS:         True (<DEFAULT>)
        CLUSTER DNS:              fake.dns (<DEFAULT>)
        CLUSTER GOSSIP PORT:      2113 (<DEFAULT>)
        GOSSIP SEED:              <empty> (<DEFAULT>)
        STATS PERIOD SEC:         30 (<DEFAULT>)
        CACHED CHUNKS:            -1 (<DEFAULT>)
        READER THREADS COUNT:     4 (<DEFAULT>)
        CHUNKS CACHE SIZE:        536871424 (<DEFAULT>)
        MAX MEM TABLE SIZE:       1000000 (<DEFAULT>)
        HASH COLLISION READ LIMIT: 100 (<DEFAULT>)
        DB:                       C:\ProgramData\chocolatey\lib\eventstore-oss\tools\EventStore-OSS-Windows-2019-v20.6.1\data (<DEFAULT>)
        INDEX:                    <empty> (<DEFAULT>)
        MEM DB:                   False (<DEFAULT>)
        SKIP DB VERIFY:           False (<DEFAULT>)
        WRITE THROUGH:            False (<DEFAULT>)
        UNBUFFERED:               False (<DEFAULT>)
        CHUNK INITIAL READER COUNT: 5 (<DEFAULT>)
        PROJECTION THREADS:       3 (<DEFAULT>)
        WORKER THREADS:           5 (<DEFAULT>)
        PROJECTIONS QUERY EXPIRY: 5 (<DEFAULT>)
        FAULT OUT OF ORDER PROJECTIONS: False (<DEFAULT>)
        ENABLE TRUSTED AUTH:      False (<DEFAULT>)
        CERTIFICATE FILE:         <empty> (<DEFAULT>)
        CERTIFICATE PRIVATE KEY FILE: <empty> (<DEFAULT>)
        CERTIFICATE PASSWORD:     <empty> (<DEFAULT>)
        CERTIFICATE RESERVED NODE COMMON NAME: eventstoredb-node (<DEFAULT>)
        DISABLE INTERNAL TCP TLS: False (<DEFAULT>)
        DISABLE EXTERNAL TCP TLS: False (<DEFAULT>)
        AUTHORIZATION TYPE:       internal (<DEFAULT>)
        AUTHENTICATION TYPE:      internal (<DEFAULT>)
        AUTHORIZATION CONFIG:     <empty> (<DEFAULT>)
        AUTHENTICATION CONFIG:    <empty> (<DEFAULT>)
        DISABLE FIRST LEVEL HTTP AUTHORIZATION: False (<DEFAULT>)
        PREPARE TIMEOUT MS:       2000 (<DEFAULT>)
        COMMIT TIMEOUT MS:        2000 (<DEFAULT>)
        WRITE TIMEOUT MS:         2000 (<DEFAULT>)
        UNSAFE DISABLE FLUSH TO DISK: False (<DEFAULT>)
        UNSAFE IGNORE HARD DELETE: False (<DEFAULT>)
        SKIP INDEX VERIFY:        False (<DEFAULT>)
        INDEX CACHE DEPTH:        16 (<DEFAULT>)
        OPTIMIZE INDEX MERGE:     False (<DEFAULT>)
        GOSSIP INTERVAL MS:       2000 (<DEFAULT>)
        GOSSIP ALLOWED DIFFERENCE MS: 60000 (<DEFAULT>)
        GOSSIP TIMEOUT MS:        2500 (<DEFAULT>)
        READ ONLY REPLICA:        False (<DEFAULT>)
        UNSAFE ALLOW SURPLUS NODES: False (<DEFAULT>)
        ENABLE HISTOGRAMS:        False (<DEFAULT>)
        LOG HTTP REQUESTS:        False (<DEFAULT>)
        LOG FAILED AUTHENTICATION ATTEMPTS: False (<DEFAULT>)
        ALWAYS KEEP SCAVENGED:    False (<DEFAULT>)
        SKIP INDEX SCAN ON READS: False (<DEFAULT>)
        REDUCE FILE CACHE PRESSURE: False (<DEFAULT>)
        INITIALIZATION THREADS:   1 (<DEFAULT>)
        MAX AUTO MERGE INDEX LEVEL: 2147483647 (<DEFAULT>)
        WRITE STATS TO DB:        False (<DEFAULT>)
        MAX TRUNCATION:           268435456 (<DEFAULT>)
        MAX APPEND SIZE:          1048576 (<DEFAULT>)
        INSECURE:                 False (<DEFAULT>)
        ENABLE ATOM PUB OVER HTTP: False (<DEFAULT>)
        DEAD MEMBER REMOVAL PERIOD SEC: 1800 (<DEFAULT>)

[36456, 1,15:17:15.730,WRN] DEPRECATED
- The Legacy TCP Client Interface has been deprecated as of version 20.6.0. The External TCP Interface can be re-enabled with the 'EnableExternalTCP' option. It is recommended to use gRPC instead.

[36456, 1,15:17:15.742,INF] Quorum size set to 1
[36456, 1,15:17:15.744,INF] TLS is enabled on at least one TCP/HTTP interface - a certificate is required to run EventStoreDB.
[36456, 1,15:17:15.769,INF] Trusted root certificate file loaded: "./trusted-root-cert\\localhost.cer"
[36456, 1,15:17:15.792,INF] Plugins path: "C:\\ProgramData\\chocolatey\\lib\\eventstore-oss\\tools\\EventStore-OSS-Windows-2019-v20.6.1\\plugins"
[36456, 1,15:17:15.792,INF] Adding: "C:\\ProgramData\\chocolatey\\lib\\eventstore-oss\\tools\\EventStore-OSS-Windows-2019-v20.6.1\\plugins" to the plugin catalog.
[36456, 1,15:17:15.915,DBG] MessageHierarchy initialization took 00:00:00.0949741.
[36456, 1,15:17:15.974,INF] "INSTANCE ID:"            fd37aad4-220b-446c-878f-d66cbd944d1b
[36456, 1,15:17:15.974,INF] "DATABASE:"               "C:\\ProgramData\\chocolatey\\lib\\eventstore-oss\\tools\\EventStore-OSS-Windows-2019-v20.6.1\\data"
[36456, 1,15:17:15.974,INF] "WRITER CHECKPOINT:"      5478 (0x1566)
[36456, 1,15:17:15.974,INF] "CHASER CHECKPOINT:"      5478 (0x1566)
[36456, 1,15:17:15.974,INF] "EPOCH CHECKPOINT:"       4971 (0x136B)
[36456, 1,15:17:15.974,INF] "TRUNCATE CHECKPOINT:"    -1 (0xFFFFFFFFFFFFFFFF)
[36456, 1,15:17:16.485,DBG] Opened ongoing "C:\\ProgramData\\chocolatey\\lib\\eventstore-oss\\tools\\EventStore-OSS-Windows-2019-v20.6.1\\data\\chunk-000000.000000" as version 3
[36456, 1,15:17:16.491,DBG] CACHED TFChunk "#0-0 (chunk-000000.000000)" in 00:00:00.0015900.
[36456, 1,15:17:16.656,INF] Starting MiniWeb for "/web/es/js/projections" ==> "C:\\ProgramData\\chocolatey\\lib\\eventstore-oss\\tools\\EventStore-OSS-Windows-2019-v20.6.1\\projections"
[36456, 1,15:17:16.656,INF] Starting MiniWeb for "/web/es/js/projections/v8/Prelude" ==> "C:\\ProgramData\\chocolatey\\lib\\eventstore-oss\\tools\\EventStore-OSS-Windows-2019-v20.6.1\\Prelude"
[36456, 1,15:17:16.667,INF] Starting MiniWeb for "/web" ==> "C:\\ProgramData\\chocolatey\\lib\\eventstore-oss\\tools\\EventStore-OSS-Windows-2019-v20.6.1\\clusternode-web"
[36456,12,15:17:16.712,INF] ========== ["0.0.0.0:2113"] SYSTEM INIT...
[36456,12,15:17:16.715,INF] Starting "Secure" TCP listening on TCP endpoint: "0.0.0.0:1113".
[36456,14,15:17:16.717,INF] TableIndex initialization...
[36456,12,15:17:16.719,INF] ========== ["0.0.0.0:2113"] Service '"StorageReader"' initialized.
[36456,12,15:17:16.719,INF] ========== ["0.0.0.0:2113"] Service '"StorageWriter"' initialized.
[36456,14,15:17:16.720,INF] ReadIndex building...
[36456,14,15:17:16.738,DBG] ReadIndex rebuilding done: total processed 23 records, time elapsed: 00:00:00.0173475.
[36456,12,15:17:16.745,INF] ========== ["0.0.0.0:2113"] Service '"StorageChaser"' initialized.
[36456,12,15:17:16.746,INF] ========== ["0.0.0.0:2113"] SYSTEM START...
[36456,12,15:17:16.747,INF] ========== ["0.0.0.0:2113"] IS UNKNOWN...
[36456, 4,15:17:16.748,DBG] Persistent subscriptions received state change to Unknown. Stopping listening
[36456,12,15:17:16.748,INF] ELECTIONS: STARTING ELECTIONS.
[36456,12,15:17:16.749,INF] ELECTIONS: (V=0) SHIFT TO LEADER ELECTION.
[36456,12,15:17:16.749,INF] ELECTIONS: (V=0) VIEWCHANGE FROM ["Unspecified/127.0.0.1:2113", {fd37aad4-220b-446c-878f-d66cbd944d1b}].
[36456,12,15:17:16.751,INF] ELECTIONS: (V=0) MAJORITY OF VIEWCHANGE.
[36456,12,15:17:16.751,INF] ELECTIONS: (V=0) SHIFT TO PREPARE PHASE.
[36456,12,15:17:16.752,INF] ELECTIONS: (V=0) PREPARE_OK FROM "[Unspecified/127.0.0.1:2113,{fd37aad4-220b-446c-878f-d66cbd944d1b}](L=5256,W=5478,C=5478,E4@4971:{6c4712b9-ef93-4f0d-9491-9d9c85b33d0f} (L={6c38a11f-b56d-49f4-9bd9-ae0e4d5ae9b4}),Priority=0)".
[36456,12,15:17:16.752,INF] ELECTIONS: (V=0) SHIFT TO REG_LEADER.
[36456,12,15:17:16.757,DBG] ELECTIONS: (V=0) Previous Leader (L={6c38a11f-b56d-49f4-9bd9-ae0e4d5ae9b4}) from last epoch record is dead, defaulting to the best candidate (B={fd37aad4-220b-446c-878f-d66cbd944d1b}).
[36456,12,15:17:16.757,DBG] ELECTIONS: (V=0) Proposing node: {fd37aad4-220b-446c-878f-d66cbd944d1b} as best leader candidate
[36456,12,15:17:16.757,INF] ELECTIONS: (V=0) SENDING PROPOSAL CANDIDATE: "[Unspecified/127.0.0.1:2113,{fd37aad4-220b-446c-878f-d66cbd944d1b}](L=5256,W=5478,C=5478,E4@4971:{6c4712b9-ef93-4f0d-9491-9d9c85b33d0f} (L={6c38a11f-b56d-49f4-9bd9-ae0e4d5ae9b4}),Priority=0)", ME: "[Unspecified/127.0.0.1:2113,{fd37aad4-220b-446c-878f-d66cbd944d1b}](L=5256,W=5478,C=5478,E4@4971:{6c4712b9-ef93-4f0d-9491-9d9c85b33d0f} (L={6c38a11f-b56d-49f4-9bd9-ae0e4d5ae9b4}),Priority=0)".
[36456,12,15:17:16.758,INF] ELECTIONS: (V=0) ACCEPT FROM ["Unspecified/127.0.0.1:2113",{fd37aad4-220b-446c-878f-d66cbd944d1b}] M=["Unspecified/127.0.0.1:2113",{fd37aad4-220b-446c-878f-d66cbd944d1b}]).
[36456,12,15:17:16.758,INF] ELECTIONS: (V=0) DONE. ELECTED LEADER = "[Unspecified/127.0.0.1:2113,{fd37aad4-220b-446c-878f-d66cbd944d1b}](L=5256,W=5478,C=5478,E4@4971:{6c4712b9-ef93-4f0d-9491-9d9c85b33d0f} (L={6c38a11f-b56d-49f4-9bd9-ae0e4d5ae9b4}),Priority=0)". ME="[Unspecified/127.0.0.1:2113,{fd37aad4-220b-446c-878f-d66cbd944d1b}](L=5256,W=5478,C=5478,E4@4971:{6c4712b9-ef93-4f0d-9491-9d9c85b33d0f} (L={6c38a11f-b56d-49f4-9bd9-ae0e4d5ae9b4}),Priority=0)".
[36456,12,15:17:16.759,INF] ========== ["0.0.0.0:2113"] PRE-LEADER STATE, WAITING FOR CHASER TO CATCH UP...
[36456, 4,15:17:16.759,DBG] Persistent subscriptions received state change to PreLeader. Stopping listening
[36456,12,15:17:16.761,INF] ========== ["0.0.0.0:2113"] IS LEADER... SPARTA!
[36456,18,15:17:16.761,DBG] Persistent subscriptions Became Leader so now handling subscriptions
[36456,12,15:17:16.761,DBG] Searching for incomplete scavenges on node "0.0.0.0:2113".
[36456,12,15:17:16.776,DBG] Max age and $ops read permission already set for the "$scavenges" stream.
[36456,10,15:17:16.789,DBG] === Writing E5@5478:{5849974b-4fd6-4fd2-8818-217156edbaaf} (previous epoch at 4971). L={fd37aad4-220b-446c-878f-d66cbd944d1b}.
[36456,10,15:17:16.793,DBG] === Update Last Epoch E5@5478:{5849974b-4fd6-4fd2-8818-217156edbaaf} (previous epoch at 4971) L={fd37aad4-220b-446c-878f-d66cbd944d1b}.
[36456,24,15:17:16.803,INF] PROJECTIONS SUBSYSTEM: Starting components for Instance: bab2c320-29ce-4cbb-bd9b-f17a252cdf9b
[36456,24,15:17:16.804,DBG] PROJECTIONS: Projection Core Coordinator component starting. Correlation: bab2c320-29ce-4cbb-bd9b-f17a252cdf9b
[36456,24,15:17:16.804,DBG] PROJECTIONS: Starting Projections Core Coordinator
[36456,24,15:17:16.804,DBG] PROJECTIONS: Starting Projections Manager. Correlation: bab2c320-29ce-4cbb-bd9b-f17a252cdf9b[36456,24,15:17:16.805,DBG] PROJECTIONS: Reading Existing Projections from "$projections-$all"
[36456,24,15:17:16.806,DBG] PROJECTIONS SUBSYSTEM: Component '"ProjectionManager"' started for Instance: bab2c320-29ce-4cbb-bd9b-f17a252cdf9b
[36456,12,15:17:16.810,DBG] No incomplete scavenges found on node "0.0.0.0:2113".
[36456,24,15:17:16.810,DBG] PROJECTIONS: SubComponent Started: "EventReaderCoreService"
[36456,24,15:17:16.810,DBG] PROJECTIONS: SubComponent Started: "EventReaderCoreService"
[36456,24,15:17:16.810,DBG] PROJECTIONS: SubComponent Started: "EventReaderCoreService"
[36456,24,15:17:16.810,DBG] PROJECTIONS: SubComponent Started: "ProjectionCoreService"
[36456,24,15:17:16.810,DBG] PROJECTIONS: SubComponent Started: "ProjectionCoreService"
[36456,24,15:17:16.810,DBG] PROJECTIONS: SubComponent Started: "ProjectionCoreService"
[36456,24,15:17:16.811,DBG] PROJECTIONS SUBSYSTEM: Component '"ProjectionCoreCoordinator"' started for Instance: bab2c320-29ce-4cbb-bd9b-f17a252cdf9b
[36456,24,15:17:16.811,INF] PROJECTIONS SUBSYSTEM: All components started for Instance: bab2c320-29ce-4cbb-bd9b-f17a252cdf9b
[36456,12,15:17:16.811,DBG] Subscription "Rules::Price": no checkpoint found
[36456,12,15:17:16.811,DBG] Start from = 0
[36456,12,15:17:16.812,INF] ========== ["0.0.0.0:2113"] Sub System '"Projections"' initialized.
[36456,24,15:17:16.814,DBG] PROJECTIONS: No projections were found in "$projections-$all", starting from empty stream
[36456,24,15:17:16.848,DBG] PROJECTIONS: Found the following new projections in "$projections-$all": ["$streams", "$stream_by_category", "$by_category", "$by_event_type", "$by_correlation_id"]
[36456,24,15:17:16.849,DBG] PROJECTIONS: Caught up with projections registration. Next expected version: 5
[36456,24,15:17:16.850,DBG] Adding projection 42b8ffef-1daa-4ce9-bd4c-f06584702c27@"$stream_by_category" to list
[36456,24,15:17:16.852,DBG] Adding projection ec4d6866-2c7a-44f6-bc64-ceb9d21590e7@"$streams" to list
[36456,24,15:17:16.852,DBG] Adding projection d09ab65e-0731-4ac4-8869-2f231301f850@"$by_event_type" to list
[36456,24,15:17:16.852,DBG] Adding projection 02a0ba3a-0ec2-4e31-99cf-ff74bda4f706@"$by_category" to list
[36456,24,15:17:16.852,DBG] Adding projection c3e27fa4-d6f5-475e-9aa7-4156634f4b04@"$by_correlation_id" to list
[36456,24,15:17:16.891,INF] '"$by_event_type"' projection source has been written
[36456,24,15:17:16.893,INF] '"$stream_by_category"' projection source has been written
[36456,24,15:17:16.893,INF] '"$by_category"' projection source has been written
[36456,24,15:17:16.893,INF] '"$streams"' projection source has been written
[36456,24,15:17:16.893,INF] '"$by_correlation_id"' projection source has been written
[36456,23,15:17:19.351,DBG] Segments count: 1, buffers count: 20, should be when full: 20

4. [https://raw.githubusercontent.com/mandeep-rubicon/images/main/2020-10-04_16-33-11.png](https://raw.githubusercontent.com/mandeep-rubicon/images/main/2020-10-04_16-33-11.png)

**EventStore details**
 - EventStore server version:  20.6.1.0,

 - Operating system: Windows 10

 - EventStore client version (if applicable):

**Additional context**

**Comment by hayley-jean** [comment] 2020-10-05 07:53
Hi @mandeep-rubicon, the atom pub API has been deprecated since version 20.6.0 of Event Store. The UI still works, but stream browsing is disabled by default.

You can enable this again by running Event Store with the `--enable-atom-pub-over-http` option

**Comment by ahjohannessen** [comment] 2020-10-05 08:08
@hayley-jean On eventstore.com under *Why use EventStoreDB?* it lists *Atom subscriptions* - Perhaps you guys should reconsider that if it is deprecated.

**Comment by jageall** [comment] 2020-10-05 12:36
> @hayley-jean On eventstore.com under _Why use EventStoreDB?_ it lists _Atom subscriptions_ - Perhaps you guys should reconsider that if it is deprecated.

I have passed it on to our marketing team, that should have been removed with 20.6.0 when it was released

**Comment by alexeyzimarev** [comment] 2020-11-06 08:33
The new website doesn't have this line. Closing it since it's by design.

**Closed by alexeyzimarev** 2020-11-06 08:33 UTC
Labels: kind/bug

**Comment by FeepingCreature** [comment] 2020-11-16 13:45
Will the Stream Browser tab be ported to the grpc interface before Atom Pub is removed?

**Comment by MaximKitsenko** [comment] 2020-11-21 03:25
And how to view streams after atom pub API deprecation?

**Comment by alexeyzimarev** [comment] 2020-11-21 10:23
There will be something else replacing the UI. The current UI stays for a while, until EOL for the AtomPub.

**Comment by dagilleland** [comment] 2021-02-03 06:22
@alexeyzimarev - Could you do a link to an issue that's working on the "something else" that will replace the UI? It would be helpful to follow into from here.
