### ISSUE TITLE
Persistent Subscriptions stalling after a few minutes

### ISSUE THREAD

**Issue by sjp** [EventStore/EventStore#2629] opened 2020-08-08 04:14 UTC
**Describe the bug**
When subscribing to a persistent subscription, we have noticed that in one of our environments the subscription appears to stall. 
 In other environments that have (to our knowledge) the same configuration, similar issues have not occurred.

What we observe is that initially, events are processed and the persistent subscription works as expected. However, after some time (~5 mins in our case) the subscriber stops receiving new events.

In the logs, it appears as though the checkpointing has failed which could the be trigger for this behaviour. We see this whenever the subscriptions stall:

```json
{ "PID": "3708", "ThreadID": "15", "Date": "2020-08-07T23:48:06.465248Z", "Level": "Debug", "Logger": "PersistentSubscriptionCheckpointWriter", "Message": "Error writing checkpoint for {stream}: {e}", "EventProperties": { "stream": "$persistentsubscription-$ce-monkey::MonkeyService-checkpoint", "e": "CommitTimeout" } }
```

**To Reproduce**
1. Create a persistent subscription (e.g. to a category stream, `$ce-monkey`)
2. Subscribe and process the events in the subscription
3. Wait for several thousand events to be processed, observe no events being sent to the client.

**Expected behavior**
The subscription receives all events from the subscription from the beginning of the stream, and continues to receive new events as they are appended to the stream.

**Actual behavior**
The subscription is partially processed and stalls before it has processed much of the stream.

**Config/Logs/Screenshots**
A relevant subset of logs attached (with some names modified). A more complete set of logs can be provided if required.

[es-subset.log](https://github.com/EventStore/EventStore/files/5044618/es-subset.log)

**EventStore details**
 - EventStore server version: v5.0.8, deployed in a cluster with one leader, 2 followers.

 - Operating system: Windows

 - EventStore client version (if applicable): v5.0.8

**Additional context**
Curiously, when we've updated the subscription to enable `Extra Statistics` we have observed that the subscription becomes "unstuck"  and events are received by the subscriber. However, this is only a temporary solution as it later becomes stuck/stalled after 5 minutes or so.

**Comment by hayley-jean** [comment] 2020-08-10 07:45
Thank you for reporting this @sjp 

It appears that the read of the `$ce-monkey` stream is timing out when the persistent subscription is trying to get new events to publish to the clients. At the moment, the persistent subscriptions won't retry expired reads which results in it getting stuck.

When you update the configuration, such as by enabling extra statistics, the persistent subscription is forced to reload from the config. This triggers a new read, which is why you saw it recover in your case.

Version 20.6.1 will include an endpoint that allows you to restart persistent subscriptions without restarting the master node.
As a workaround for right now, you can continue to update configuration to restore a stuck subscription. However we also recommend that you investigate the cause behind the read expiry on this node.

**Comment by sjp** [comment] 2020-08-10 09:42
Hi @hayley-jean , thanks for the update. I have a few questions and some good news.

We have updated some of the machines hosting our cluster, and changed some configuration which appears to have resolved the problem we were encountering with the projections. We're no longer getting any stalling!

Regarding the workaround, we fortunately won't need to use it but it's good to know that it has this effect. However, the failure mode here seems like it could be improved a bit. Could you explain why there is no retry policy when this scenario occurs?

To me, stalling without providing any information that this has occurred is a sub-optimal outcome. Persistent subscriptions are a useful tool, but if you have to hand-hold it to get it to work, it's difficult to rely upon it for production workloads (i.e. we don't want to constant monitor it to make sure it's running). Is there any way to determine whether this has occurred outside of logs? e.g. client exceptions, dashboard warnings, management API stats, etc.

This could be unrelated, but we have had some problems in the past where projections will periodically fail and require restarting. Does it also exhibit the same failure mode as persistent subscriptions, where an expired read could cause it to get stuck? Similarly I believe a retry policy in this situation would likely resolve the problem.

While I appreciate that in v20.6.1, the persistent subscription subsystem can be restarted independently, I would rather it not be necessary. Without knowing the specifics and internals of EventStore in-depth, is it not possible to be a bit more self-healing (e.g. detect something is stuck/broken, auto-restart)?

**Comment by ekjuanrejon** [comment] 2020-08-11 10:59
I am encountering the same issue but with catch up subscriptions. If I run all my integration test at once like the catch subscription freezes. I have to restart the subscription manually.

I am using 20.6.0. I am running it inside docker

**Comment by hayley-jean** [comment] 2020-08-11 11:16
> I am encountering the same issue but with catch up subscriptions. If I run all my integration test at once like the catch subscription freezes. I have to restart the subscription manually.
> 
> I am using 20.6.0. I am running it inside docker

@ekjuanrejon Thanks for reporting this!
Would you mind opening a separate issue for this? The catchup subscriptions are different to persistent subscriptions, as they are handled by the client rather than the server.

If you are using the dotnet gRPC client, could you please open the issue in the [client repo](https://github.com/EventStore/EventStore-Client-Dotnet), otherwise you can open it in this one.

**Comment by oskardudycz** [comment] 2022-02-02 09:15
@sjp, we added retries in the `21.10` version, could you check if you're not getting into that issue while using the latest version? I'm going to close this issue, but if that's still the case, I'll reopen it.

**Closed by oskardudycz** 2022-02-02 09:15 UTC
Labels: kind/bug, subsystem/persistent subs, detectability/easy

**Comment by sjp** [comment] 2022-02-02 19:25
Thanks @oskardudycz. We're in the process of upgrading to the latest version.

Fortunately we haven't encountered this issue recently (a lot of factors could contribute to that) but good to know it's fixed.

**Comment by oskardudycz** [comment] 2022-02-02 19:45
@sjp, thanks for the feedback 👌 If you’re also considering migration from TCP to gRPC client; we received recently published a migration guide: https://developers.eventstore.com/clients/dotnet/21.2/migration-to-gRPC.html#appending-events.
