### ISSUE TITLE
Crashes on startup with "too small array"

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#2604] opened 2020-07-17 05:13 UTC
**Describe the bug**

Crashes on startup after out of disk error:

```
[00001,07,05:09:54.419] Error in TableIndex.ReadOffQueue
EXCEPTION OCCURRED
array too small. numBytes/offset wrong.
Parameter name: array
[00001,07,05:09:54.437] Global Unhandled Exception occurred.
EXCEPTION OCCURRED
array too small. numBytes/offset wrong.
Parameter name: array
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: array too small. numBytes/offset wrong.
Parameter name: array
  at System.IO.FileStream.Dispose (System.Boolean disposing) [0x000cb] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
  at System.IO.Stream.Close () [0x00000] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
  at System.Security.Cryptography.CryptoStream.Dispose (System.Boolean disposing) [0x00011] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
  at System.IO.Stream.Close () [0x00000] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
  at System.IO.Stream.Dispose () [0x00000] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
  at EventStore.Core.Index.PTable.MergeTo2 (System.Collections.Generic.IList`1[T] tables, System.Int64 numIndexEntries, System.Int32 indexEntrySize, System.String outputFile, System.Func`3[T1,T2,TResult] upgradeHash, System.Func`2[T,TResult] existsAt, System.Func`2[T,TResult] readRecord, System.Byte version, System.Int32 cacheDepth, System.Boolean skipIndexVerify) [0x002b3] in <00777c483d494830ae16c20f0a7f6d6a>:0
  at EventStore.Core.Index.PTable.MergeTo (System.Collections.Generic.IList`1[T] tables, System.String outputFile, System.Func`3[T1,T2,TResult] upgradeHash, System.Func`2[T,TResult] existsAt, System.Func`2[T,TResult] readRecord, System.Byte version, System.Int32 cacheDepth, System.Boolean skipIndexVerify) [0x00090] in <00777c483d494830ae16c20f0a7f6d6a>:0
  at EventStore.Core.Index.IndexMap.AddPTableForAutomaticMerge (EventStore.Core.Index.PTable tableToAdd, System.Int64 prepareCheckpoint, System.Int64 commitCheckpoint, System.Func`3[T1,T2,TResult] upgradeHash, System.Func`2[T,TResult] existsAt, System.Func`2[T,TResult] recordExistsAt, EventStore.Core.Index.IIndexFilenameProvider filenameProvider, System.Byte version, System.Int32 indexCacheDepth, System.Boolean skipIndexVerify) [0x0006a] in <00777c483d494830ae16c20f0a7f6d6a>:0
  at EventStore.Core.Index.IndexMap.AddPTable (EventStore.Core.Index.PTable tableToAdd, System.Int64 prepareCheckpoint, System.Int64 commitCheckpoint, System.Func`3[T1,T2,TResult] upgradeHash, System.Func`2[T,TResult] existsAt, System.Func`2[T,TResult] recordExistsAt, EventStore.Core.Index.IIndexFilenameProvider filenameProvider, System.Byte version, System.Int32 level, System.Int32 indexCacheDepth, System.Boolean skipIndexVerify) [0x0002d] in <00777c483d494830ae16c20f0a7f6d6a>:0
  at EventStore.Core.Index.TableIndex.ReadOffQueue () [0x0028d] in <00777c483d494830ae16c20f0a7f6d6a>:0
  at EventStore.Core.Index.TableIndex.<TryProcessAwaitingTables>b__44_0 (System.Object x) [0x00000] in <00777c483d494830ae16c20f0a7f6d6a>:0
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
```

How to get the database back up?

**To Reproduce**
1. Make it OOM
2. Start it, maybe you get this bug

**Expected behavior**
To start

**Actual behavior**
Crashes

**Config/Logs/Screenshots**
Single node

**EventStore details**
 - EventStore server version: eventstore/eventstore@sha256:7802b86e3175de09436515010418336a656e1fb7eace2e85da89933076cdd863

 - Operating system: COS / as in image

 - EventStore client version (if applicable): N/A

**Comment by oskardudycz** [comment] 2022-02-09 09:21
Closing as it's a duplicate of https://github.com/EventStore/EventStore/issues/3024. See further discussion there.

**Closed by oskardudycz** 2022-02-09 09:21 UTC
Labels: kind/bug
