### ISSUE TITLE
Subscription to all - determine whether stream was deleted

### ISSUE THREAD

**Issue by MadSciencist** [EventStore/EventStore#2793] opened 2021-01-20 15:35 UTC
**Is your feature request related to a problem? Please describe.**
Hey,
I'm using .NET client and SubscribeToAllFrom() method to subscribe to every event, then I'm looking only for known (such events t hat can be handled by application) events. The issue is that the $all stream contains all the events - even hard deleted ones. When I'm doing replays unfortunately these also get projected.

**Describe the solution you'd like**
Some sort of mechanism that will allow me determine whether the stream was deleted.

**Describe alternatives you've considered**
Create $by_category projection and subscribe to individual categories. Looks like ES is skipping removed events there.

**Comment by alexeyzimarev** [comment] 2021-03-15 15:18
The issue is indeed annoying, but it's more like a design choice. The `$all` stream represents the physical event log as it is written on disk. When you delete streams, or events get deleted by stream truncation, max age or max count, they physically remain on disk until you run the scavenge process. During scavenging, the server will compact the chunk files by removing deleted events, so those events won't be popping up in a subscription to `$all`.

The scavenge process doesn't touch the active chunk, as events are currently being written to it, so we can't just close this file and start compacting it. As a result, recent deletions won't be scavenged and you will get deleted events in your subscriptions. In addition, when the database size is small, you always work on the active chunk and events will never be physically deleted.

Theoretically, the server can check the stream metadata when returning events to the subscription. But it will result in severe performance degradation, or substantial memory usage increase, as the server would need to read the stream metadata for each returned event, or/and keep the meta in the cache.

You rightfully mentioned that this becomes an issue when you need to replay. Under normal production scenarios that won't be a real problem as deleted events would be scavenged. If the subscription is always reading real-time, it won't even need to bother about deletions.

**Comment by alexeyzimarev** [comment] 2021-03-15 15:19
And yes, when you read from any stream, which consists of link events, and use `resolveLinkTos`, the server will check the stream meta when resolving the link.

**Comment by oskardudycz** [comment] 2022-01-19 10:10
Closing it because of inactivity and primarily because, as @alexeyzimarev described, it's more of a current design choice than a bug.

**Closed by oskardudycz** 2022-01-19 10:10 UTC
Labels: kind/enhancement
