### ISSUE TITLE
Event at checkpoint tag $ce-<stream>: <event> has been already processed

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2532] opened 2020-06-08 09:47 UTC
**Describe the bug**
Projection can fault with the following error:
```
[15995,21,09:38:04.473] The '"test"' projection faulted due to '"Event at checkpoint tag $ce-test: 123 has been already processed
  at EventStore.Projections.Core.Services.Processing.PositionTracker.UpdateByCheckpointTagForward (EventStore.Projections.Core.Services.Processing.CheckpointTag newTag) [0x00032] in <c1b624df8d2946ba92159e391556de3b>:0 
  at EventStore.Projections.Core.Services.Processing.CoreProjectionCheckpointManager.EventProcessed (EventStore.Projections.Core.Services.Processing.CheckpointTag checkpointTag, System.Single progress) [0x00030] in <c1b624df8d2946ba92159e391556de3b>:0 
  at EventStore.Projections.Core.Services.Processing.EventSubscriptionBasedProjectionProcessingPhase.FinalizeEventProcessing (EventStore.Projections.Core.Services.Processing.EventProcessedResult result, EventStore.Projections.Core.Services.Processing.CheckpointTag eventCheckpointTag, System.Single progress) [0x000df] in <c1b624df8d2946ba92159e391556de3b>:0 
  at EventStore.Projections.Core.Services.Processing.PartitionDeletedWorkItem.WriteOutput () [0x00032] in <c1b624df8d2946ba92159e391556de3b>:0 
  at EventStore.Projections.Core.Services.Processing.WorkItem.Process (System.Int32 onStage, System.Action`2[T1,T2] readyForStage) [0x00086] in <c1b624df8d2946ba92159e391556de3b>:0 
  at EventStore.Projections.Core.Services.Processing.StagedProcessingQueue.ProcessEntry (EventStore.Projections.Core.Services.Processing.StagedProcessingQueue+TaskEntry entry) [0x00037] in <c1b624df8d2946ba92159e391556de3b>:0 
  at EventStore.Projections.Core.Services.Processing.StagedProcessingQueue.Process (System.Int32 max) [0x0001c] in <c1b624df8d2946ba92159e391556de3b>:0 
  at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessOneEventBatch () [0x00019] in <c1b624df8d2946ba92159e391556de3b>:0 
  at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessEvent () [0x00010] in <c1b624df8d2946ba92159e391556de3b>:0 
  at EventStore.Projections.Core.Services.Processing.EventSubscriptionBasedProjectionProcessingPhase.ProcessEvent () [0x00000] in <c1b624df8d2946ba92159e391556de3b>:0 
  at EventStore.Projections.Core.Services.Processing.CoreProjection.Tick () [0x0002c] in <c1b624df8d2946ba92159e391556de3b>:0 "'
```

**To Reproduce**
1. Start EventStore 5.0.8 with --run-projections=All
2. Create a continuous projection called `test` with the following source:
```
fromCategory('test')
.foreachStream()
.when({
    '$any':function(s,e){
    }
});
```
3. Make sure the projection `test` is started
4. Start the projection `$by_category`
5. Run the following shell command to trigger 10 concurrent stream delete requests:
```
for i in `seq 1 10`; do curl -v -u "admin:changeit" -X DELETE "http://127.0.0.1:2113/streams/test-hello" &; sleep 0.01; done
```
6. The projection will fault with the above error
7. The projection should continue without errors after being stopped and started (as a workaround)

**Expected behavior**
The projection should not fault

**Actual behavior**
The projection has faulted

**Screenshot**
![Screenshot from 2020-06-08 13-39-29](https://user-images.githubusercontent.com/14981676/84015954-a7dd4300-a98d-11ea-955e-b2ea861c8024.png)

**EventStore details**
 - EventStore server version: 5.0.8

 - Operating system: Tested on Ubuntu 16.04

**Comment by shaan1337** [comment] 2020-06-22 10:04
Just adding this one-liner to help with fixing the issue faster later (works on linux/master branch)
```
pkill -9 -f ClusterNode; rm ../db -rf; dotnet bin/Release/EventStore.ClusterNode/netcoreapp3.1/linux-x64/EventStore.ClusterNode.dll --db ../db --dev --run-projections=All &; sleep 2; curl -XPOST -k -v -u "admin:changeit" https://127.0.0.1:2113/projections/continuous\?name\=test\&type\=js\&enabled\=true\&emit\=true\&trackemittedstreams\=false -d 'fromCategory("test").foreachStream().when({"$any":function(s,e){}});'; sleep 2; curl -u "admin:changeit" -X POST -H "Content-Length: 0" -u "admin:changeit" -k 'https://localhost:2113/projection/$by_category/command/enable' ; sleep 2; for i in `seq 1 10`; do curl -v -u "admin:changeit" -k -X DELETE "https://127.0.0.1:2113/streams/test-hello" &; sleep 0.01; done
```

**Comment by hayley-jean** [comment] 2020-07-06 08:29
This issue is caused by $deleted metadata events that can no longer be resolved.
When this happens, they end up being handled both as a deleted event and as a committed event rather than one or the other.

For example:

1. `test-hello` is deleted, this results in a `$tb` metadata event being written to `$$test-hello`
2. The deleted metadata event from 1 is handled by the `$by_category` projection.
    This emits a link of the metadata event to the `$ce-test` stream.
3. Before the `test` projection can handle the link in the `$ce-test` stream, new metadata is written to `$$test-hello`.
    This means that the original metadata event can no longer be read.
4. The `test` projection now handles the link in `$ce-test`. 
    This event does not resolve, but the event reader can still determine that it's a deleted event by checking for `$deleted` metadata in the link event itself [here](https://github.com/EventStore/EventStore/blob/master/src/EventStore.Projections.Core/Services/Processing/TransactionFileEventReader.cs#L177).
5. The event reader publishes a `PartitionDeleted` message as well as a `CommittedEventDistributed` message ([see here](https://github.com/EventStore/EventStore/blob/master/src/EventStore.Projections.Core/Services/Processing/TransactionFileEventReader.cs#L189)).
6. The committed event gets to the `ReaderSubscriptionBase`. This checks whether the event passes the filter in order to process it [here](https://github.com/EventStore/EventStore/blob/master/src/EventStore.Projections.Core/Services/Processing/ReaderSubscriptionBase.cs#L103).

This is the point where the issue occurs. Deleted events are usually filtered out of the check. However, the deleted check determines this by checking for `$tb` values in the metadata of the [resolved event](https://github.com/EventStore/EventStore/blob/master/src/EventStore.Projections.Core/Services/Processing/ResolvedEvent.cs#L199). Given the event cannot be resolved, this check determines that the event is not deleted, and so it handles it.

This results in the `PositionTracker` being updated for the `CommittedEventDistributed` message.

When the `PartitionDeleted` message eventually gets handled, this also updates the `PositionTracker` which causes the error.

**Closed** 2020-07-15 08:52 UTC
Labels: backport, customer initiated, kind/bug, subsystem/projections
