### ISSUE TITLE
Regular Expression for server side filtering kills eventstore

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#3391] opened 2022-01-20 08:44 UTC
**Describe the bug**
Setting a specific regular expression for StreamFilter.RegularExpression (I haven't been brave enough to try EventTypeFilter) causes the evenstore to stop running, and continues to repeat the error on restart.
This is for a Persistent Subscription

**To Reproduce**

```
var filter = StreamFilter.RegularExpression("\b(?!SalesTransactionAggregate\b)\w+");
await client.CreateToAllAsync(groupName,
                                          filter,
                                          settings);
```

**Expected behavior**
If the regular expression is invalid (the persistent subscription should have been rejected.

**Actual behavior**
It appears as if the persistent subscription was created, and the evenstore continues to try and parse this regular expression.

**Config/Logs/Screenshots**

_{"@t":"2022-01-20T00:32:34.2094236Z","@mt":"Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application.","@l":"Error","@x":"System.UriFormatException: Invalid URI: The hostname could not be parsed.\n at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)\n at EventStore.Transport.Http.EntityManagement.CoreHttpRequestAdapter.get_Url() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Transport.Http/EntityManagement/CoreHttpRequestAdapter.cs:line 32\n at EventStore.Transport.Http.EntityManagement.HttpEntity.BuildRequestedUrl(IHttpRequest request, String advertiseAsAddress, Int32 advertiseAsPort, Boolean overridePath) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Transport.Http/EntityManagement/HttpEntity.cs:line 41\n at EventStore.Transport.Http.EntityManagement.HttpEntity..ctor(HttpContext context, Boolean logHttpRequests, String advertiseAsHost, Int32 advertiseAsPort, Action onComplete) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Transport.Http/EntityManagement/HttpEntity.cs:line 26\n at EventStore.Core.Services.Transport.Http.KestrelToInternalBridgeMiddleware.TryMatch(HttpContext context, IUriRouter uriRouter, Boolean logHttpRequests, String advertiseAsAddress, Int32 advertiseAsPort) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Transport/Http/KestrelToInternalBridgeMiddleware.cs:line 91\n at EventStore.Core.Services.Transport.Http.KestrelToInternalBridgeMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Transport/Http/KestrelToInternalBridgeMiddleware.cs:line 198\n at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\n--- End of stack trace from previous location ---\n at EventStore.Core.Services.Transport.Http.AuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Transport/Http/AuthenticationMiddleware.cs:line 26\n at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\n--- End of stack trace from previous location ---\n at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)\n at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)","ConnectionId":"0HMDG3NTNL977","TraceIdentifier":"0HMDG3NTNL977:00000002","EventId":{"Id":13,"Name":"ApplicationError"},"SourceContext":"Microsoft.AspNetCore.Server.Kestrel","RequestId":"0HMDG3NTNL977:00000002","RequestPath":"/","ProcessId":3227,"ThreadId":108}_

**EventStore details**
 - EventStore server version: 21.6

 - Operating system:

 - EventStore client version (if applicable): 21.2.1-alpha.0.28

**Comment by StevenBlair123** [comment] 2022-01-20 08:54
The Evenstore I tested this on no longer starts. The services is on an auto restart, and we cna get sometiems get to the dashboard / projections tab before it falls again.

**Comment by oskardudycz** [comment] 2022-01-24 09:26
@jageall, @timothycoleman, were you able to reproduce the issue?

I think that we should also make sure that we're validating regexp in all subscription filters both on clients and database level.

**Comment by hayley-jean** [comment] 2022-01-24 14:36
@StevenBlair123 we've not been able to reproduce this issue. Could you provide more logs showing the server crash and restarts?

**Comment by StevenBlair123** [comment] 2022-01-24 19:27
@hayley-jean - we passed over all the logs that we had.
We have been trying to replicate the issue here as well, without any luck.
The server started back up after we deleted the subscription (I ran a console app which flooded the service with a Delete request)

**Comment by shaan1337** [comment] 2022-01-25 04:57
@StevenBlair123 do you still have the chunk files from the database that won't start up and would it be feasible for you to share them?

**Comment by StevenBlair123** [comment] 2022-01-25 08:47
@shaan1337  - I will ask the powers that be if we can share.

**Comment by timothycoleman** [comment] 2022-01-25 14:19
Spent some time with @StevenBlair123 on this, looks like it was the deadlock that can sometimes occur when creating a persistent subscription in 21.6 https://github.com/EventStore/EventStore/pull/3344, which has since been fixed. The nature of the regex and the uriexception appear to be red-herrings in this case.

Side note, the server does validate the provided regex and will fail the grpc call without creating the subscription if it doesn't parse

**Comment by StevenBlair123** [comment] 2022-01-25 14:24
@timothycoleman - thanks a lot for this.

**Comment by timothycoleman** [comment] 2022-01-25 14:41
Welcome - I'll close this, let me know if there's anything further

**Closed by timothycoleman** 2022-01-25 14:41 UTC
Labels: kind/bug, subsystem/persistent subs, action/close if no further feedback
