### ISSUE TITLE
Something is off with volatile subscriptions

### ISSUE THREAD

**Issue by SzymonPobiega** [EventStore/EventStore#860] opened 2016-03-22 10:44 UTC
When I use a volatile subscription on a connection, I am unable to close that connection. Here's a repro test:

```
[Test]
public async Task VerifyThatSubscriptionWork()
{
    var closeEvent = new ManualResetEventSlim(false);
    var connection = EventStoreConnection.Create(new IPEndPoint(IPAddress.Loopback, 1113));

    await connection.ConnectAsync().ConfigureAwait(false);
    var streamName = Guid.NewGuid().ToString();

    //var sub = await connection.SubscribeToStreamAsync(streamName, true, (subscription, e) => { }).ConfigureAwait(false);
    var sub = connection.SubscribeToStreamAsync(streamName, true, (subscription, e) => { }).GetAwaiter().GetResult();

    sub.Unsubscribe();

    //Verify closed
    connection.Closed += (sender, args) =>
    {
        Console.WriteLine("Closed");
        closeEvent.Set();
    };
    connection.Close();
    if (!closeEvent.Wait(TimeSpan.FromSeconds(5)))
    {
        Console.WriteLine("Failed to close connection {0}", connection.ConnectionName);
    }
    else
    {
        Console.WriteLine("Close signalled via event");
    }
}
```

if you uncomment the `async` subscribe, the connection does not get closed. Well, it does get but too late (when I attach a debugger I can see that `Closed` event is indeed executed but the test is already finished).

**Comment by gregoryyoung** [comment] 2016-03-22 10:47
3.5.0?

What do you get with verbose logging enabled

**Comment by SzymonPobiega** [comment] 2016-03-22 10:56
3.5.2

Here's the log
```

[05,10:54:39.178,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': enqueueing message EventStore.ClientAPI.Internal.StartConnectionMessage..
[08,10:54:39.183,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': StartConnection.
[08,10:54:39.184,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': DiscoverEndPoint.
[08,10:54:39.187,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
[08,10:54:39.188,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': enqueueing message EventStore.ClientAPI.Internal.StartSubscriptionMessage..
[04,10:54:39.191,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': EstablishTcpConnection to [127.0.0.1:1113].
[04,10:54:39.249,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': StartSubscription enqueue VolatileSubscriptionOperation, EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, 10, 00:00:07..
[08,10:54:39.262,DEBUG] TcpPackageConnection: connected to [127.0.0.1:1113, L127.0.0.1:58729, {c1b04443-e13d-47dd-9aa7-3ccad641986c}].
[08,10:54:39.263,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionEstablishedMessage..
[08,10:54:39.265,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': TCP connection to [127.0.0.1:1113, L127.0.0.1:58729, {c1b04443-e13d-47dd-9aa7-3ccad641986c}] established..
[11,10:54:39.962,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': enqueueing message EventStore.ClientAPI.Internal.HandleTcpPackageMessage..
[04,10:54:39.971,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': HandleTcpPackage connId c1b04443-e13d-47dd-9aa7-3ccad641986c, package HeartbeatRequestCommand, 1c4d7210-de47-4eb8-9da9-6483ea2b92c4..
[11,10:54:40.325,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': enqueueing message EventStore.ClientAPI.Internal.HandleTcpPackageMessage..
[10,10:54:40.325,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': StartSubscription SUBSCRIBING Subscription VolatileSubscriptionOperation (567d454f-eac7-4307-9f6e-34867946c92b): EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, is subscribed: False, retry count: 0, created: 10:54:39.250, last updated: 10:54:40.218..
[10,10:54:40.326,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': HandleTcpPackage connId c1b04443-e13d-47dd-9aa7-3ccad641986c, package SubscriptionConfirmation, 567d454f-eac7-4307-9f6e-34867946c92b..
[10,10:54:40.343,DEBUG] Subscription {567d454f-eac7-4307-9f6e-34867946c92b} to 8a1cd321-8d8d-4da6-9827-5bef52d151ea: subscribed at CommitPosition: 719904, EventNumber: -1.
[10,10:54:40.345,DEBUG] Subscription {567d454f-eac7-4307-9f6e-34867946c92b} to 8a1cd321-8d8d-4da6-9827-5bef52d151ea: closing subscription, reason: UserInitiated, exception: ...
[11,10:54:40.347,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': enqueueing message EventStore.ClientAPI.Internal.HandleTcpPackageMessage..
10:54:40>> Calling Close
[10,10:54:40.348,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': enqueueing message EventStore.ClientAPI.Internal.CloseConnectionMessage..
[11,10:54:41.347,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': enqueueing message EventStore.ClientAPI.Internal.HandleTcpPackageMessage..
[11,10:54:42.051,INFO] ClientAPI TcpConnection closed [10:54:42.051: N127.0.0.1:1113, L127.0.0.1:58729, {c1b04443-e13d-47dd-9aa7-3ccad641986c}]:
Received bytes: 103, Sent bytes: 106
Send calls: 3, callbacks: 3
Receive calls: 5, callbacks: 5
Close reason: [Success] Socket closed

[11,10:54:42.061,DEBUG] TcpPackageConnection: connection [127.0.0.1:1113, L127.0.0.1:58729, {c1b04443-e13d-47dd-9aa7-3ccad641986c}] was closed cleanly.
[11,10:54:42.063,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
10:54:50>> Failed to close connection ES-957f937f-c2cb-4fc3-b166-ecef137c2cac
[10,10:54:50.352,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': HandleTcpPackage SUBSCRIPTION DECISION Subscribed (SubscriptionConfirmation), Subscription VolatileSubscriptionOperation (567d454f-eac7-4307-9f6e-34867946c92b): EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, is subscribed: False, retry count: 0, created: 10:54:39.250, last updated: 10:54:40.218.
[10,10:54:50.354,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': HandleTcpPackage connId c1b04443-e13d-47dd-9aa7-3ccad641986c, package SubscriptionDropped, 567d454f-eac7-4307-9f6e-34867946c92b..
```

**Comment by gregoryyoung** [comment] 2016-03-22 11:00
I seem to remember some oddities with nunit async causing issues in things @pgermishuys pointed me over to this thread https://github.com/EventStore/EventStore/issues/712

Does it work as a synchronous test?

**Comment by SzymonPobiega** [comment] 2016-03-22 11:04
I added this in the beginning of the test:

```
[Test]
        public void SyncTestWrapper()
        {
            VerifyThatSubscriptionWork().GetAwaiter().GetResult();
        }

        async Task VerifyThatSubscriptionWork()
        {
```

and got same results so I think it is not related to NUnit. I can also reproduce it in my acceptance tests for NSB transport. I have 4 connections there and only the one with volatile subscription seems to be hanging after the test is executed. It is only killed when shutting down NUnit/process/app domain.

**Comment by SzymonPobiega** [comment] 2016-03-22 11:06
Here's the log when I call `Subscribe` with `GetAwaiter().GetResult`:

```

[05,11:05:58.056,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': enqueueing message EventStore.ClientAPI.Internal.StartConnectionMessage..
[08,11:05:58.061,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': StartConnection.
[08,11:05:58.062,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': DiscoverEndPoint.
[08,11:05:58.065,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': enqueueing message EventStore.ClientAPI.Internal.EstablishTcpConnectionMessage..
[08,11:05:58.066,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': enqueueing message EventStore.ClientAPI.Internal.StartSubscriptionMessage..
[04,11:05:58.069,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': EstablishTcpConnection to [127.0.0.1:1113].
[04,11:05:58.125,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': StartSubscription enqueue VolatileSubscriptionOperation, EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, 10, 00:00:07..
[04,11:05:58.136,DEBUG] TcpPackageConnection: connected to [127.0.0.1:1113, L127.0.0.1:58949, {3382a610-0b63-4369-940a-5ae8663b9739}].
[04,11:05:58.137,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionEstablishedMessage..
[04,11:05:58.140,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': TCP connection to [127.0.0.1:1113, L127.0.0.1:58949, {3382a610-0b63-4369-940a-5ae8663b9739}] established..
[11,11:05:58.830,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': enqueueing message EventStore.ClientAPI.Internal.HandleTcpPackageMessage..
[04,11:05:58.833,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': HandleTcpPackage connId 3382a610-0b63-4369-940a-5ae8663b9739, package HeartbeatRequestCommand, 79e8a30b-dd94-48dd-acae-a166f078065d..
[11,11:05:59.172,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': enqueueing message EventStore.ClientAPI.Internal.HandleTcpPackageMessage..
[04,11:05:59.172,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': StartSubscription SUBSCRIBING Subscription VolatileSubscriptionOperation (34db5708-d902-4c8f-b831-72b3a9236807): EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, is subscribed: False, retry count: 0, created: 11:05:58.126, last updated: 11:05:59.097..
[04,11:05:59.173,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': HandleTcpPackage connId 3382a610-0b63-4369-940a-5ae8663b9739, package SubscriptionConfirmation, 34db5708-d902-4c8f-b831-72b3a9236807..
[04,11:05:59.190,DEBUG] Subscription {34db5708-d902-4c8f-b831-72b3a9236807} to f858c85b-1d4f-409a-9ea7-2ff12c836134: subscribed at CommitPosition: 1060162, EventNumber: -1.
[04,11:05:59.192,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': HandleTcpPackage SUBSCRIPTION DECISION Subscribed (SubscriptionConfirmation), Subscription VolatileSubscriptionOperation (34db5708-d902-4c8f-b831-72b3a9236807): EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, is subscribed: False, retry count: 0, created: 11:05:58.126, last updated: 11:05:59.097.
[08,11:05:59.193,DEBUG] Subscription {34db5708-d902-4c8f-b831-72b3a9236807} to f858c85b-1d4f-409a-9ea7-2ff12c836134: closing subscription, reason: UserInitiated, exception: ...
[11,11:05:59.194,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': enqueueing message EventStore.ClientAPI.Internal.HandleTcpPackageMessage..
[10,11:05:59.195,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': HandleTcpPackage connId 3382a610-0b63-4369-940a-5ae8663b9739, package SubscriptionDropped, 34db5708-d902-4c8f-b831-72b3a9236807..
11:05:59>> Calling Close
[08,11:05:59.196,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': enqueueing message EventStore.ClientAPI.Internal.CloseConnectionMessage..
[10,11:05:59.206,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': HandleTcpPackage SUBSCRIPTION DECISION EndOperation (SubscriptionDropped: Unsubscribed), Subscription VolatileSubscriptionOperation (34db5708-d902-4c8f-b831-72b3a9236807): EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, is subscribed: True, retry count: 0, created: 11:05:58.126, last updated: 11:05:59.097.
[10,11:05:59.207,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': RemoveSubscription Subscription VolatileSubscriptionOperation (34db5708-d902-4c8f-b831-72b3a9236807): EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, is subscribed: True, retry count: 0, created: 11:05:58.126, last updated: 11:05:59.097, result True..
[10,11:05:59.208,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': CloseConnection, reason Connection close requested by client., exception ..
[10,11:05:59.214,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': CloseTcpConnection.
[10,11:05:59.216,INFO] ClientAPI TcpConnection closed [11:05:59.216: N127.0.0.1:1113, L127.0.0.1:58949, {3382a610-0b63-4369-940a-5ae8663b9739}]:
Received bytes: 81, Sent bytes: 106
Send calls: 3, callbacks: 3
Receive calls: 4, callbacks: 3
Close reason: [Success] Connection close requested by client.

[10,11:05:59.222,DEBUG] TcpPackageConnection: connection [127.0.0.1:1113, L127.0.0.1:58949, {3382a610-0b63-4369-940a-5ae8663b9739}] was closed cleanly.
[10,11:05:59.223,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
[10,11:05:59.224,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': IGNORED (_state: Closed, _conn.ID: {3382a610-0b63-4369-940a-5ae8663b9739}, conn.ID: {3382a610-0b63-4369-940a-5ae8663b9739}): TCP connection to [127.0.0.1:1113, L127.0.0.1:58949] closed..
[10,11:05:59.225,INFO] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': Closed. Reason: Connection close requested by client...
11:05:59:>> Closed
11:05:59>> Close signalled via event
[10,11:05:59.227,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': IGNORED (_state: Closed, _conn.ID: {00000000-0000-0000-0000-000000000000}, conn.ID: {3382a610-0b63-4369-940a-5ae8663b9739}): TCP connection to [127.0.0.1:1113, L127.0.0.1:58949] closed..

```

**Comment by SzymonPobiega** [comment] 2016-03-22 11:08
These lines seem to be displaced

```
[04,11:05:59.192,DEBUG] EventStoreConnection 'ES-cf3ba63e-24b9-4831-998b-947dc197159e': HandleTcpPackage SUBSCRIPTION DECISION Subscribed (SubscriptionConfirmation), Subscription VolatileSubscriptionOperation (34db5708-d902-4c8f-b831-72b3a9236807): EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, is subscribed: False, retry count: 0, created: 11:05:58.126, last updated: 11:05:59.097.
```

In the first log they only show when stopping the process.

**Comment by gregoryyoung** [comment] 2016-03-22 11:09
I was looking more at:

[11,10:54:42.061,DEBUG] TcpPackageConnection: connection [127.0.0.1:1113, L127.0.0.1:58729, {c1b04443-e13d-47dd-9aa7-3ccad641986c}] was closed cleanly.
[11,10:54:42.063,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
10:54:50>> Failed to close connection ES-957f937f-c2cb-4fc3-b166-ecef137c2cac
[10,10:54:50.352,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': HandleTcpPackage SUBSCRIPTION DECISION Subscribed (SubscriptionConfirmation), Subscription VolatileSubscriptionOperation (567d454f-eac7-4307-9f6e-34867946c92b): EventStore.ClientAPI.ClientOperations.VolatileSubscriptionOperation, is subscribed: False, retry count: 0, created: 10:54:39.250, last updated: 10:54:40.218.
[10,10:54:50.354,DEBUG] EventStoreConnection 'ES-957f937f-c2cb-4fc3-b166-ecef137c2cac': HandleTcpPackage connId c1b04443-e13d-47dd-9aa7-3ccad641986c, package SubscriptionDropped, 567d454f-eac7-4307-9f6e-34867946c92b..

**Comment by SzymonPobiega** [comment] 2016-03-22 14:20
FYI, I noticed the same behavior occurs even when there is no `Unsubscribe`, just subscribe and then close the connection. I've went through the code and the subscribe op does not seem to be different from any other operation in the sense all of them use `TaskCompletionSource<T>`.

I have no idea what can be wrong there. I am far from being an expert in async stuff. All I noticed by looking at the code is that `SubscriptionOperation::ConfirmSubscription` ends up being blocked in `SetResult` so that the user code gets the `Subscription` and can continue but the message processing thread sits in place.

**Comment by gregoryyoung** [comment] 2016-04-01 14:17
Can you try this against 3.6.0 (dev) there are a slew of changes there.

**Comment by hayley-jean** [comment] 2016-04-04 07:46
@SzymonPobiega As you said in your last message, the message processing thread is getting blocked after SetResult is called. This is because of a bug in the .NET async library ([details here](https://connect.microsoft.com/VisualStudio/feedback/details/769322/waiting-on-task-can-deadlock-in-free-threaded-context)). Basically the issue is that when you set the result on a TaskCompletionSource, control is returned to the awaiting method (your test) on the same thread that set the result.

This means that this line: ```if (!closeEvent.Wait(TimeSpan.FromSeconds(5)))``` is executed on the message processing thread, blocking the thread and preventing any more messages from being processed until after the timeout. This is why you always see the closeEvent fired after your test has finished running - the thread is no longer blocked and it can continue processing messages.

The fix for this is to await that timeout as well, rather than blocking the thread with .Wait(). This can be done by replacing your ManualResetEvent with a TaskCompletionSource and awaiting it along with a Task.Delay for a timeout :


```
[Test]
public async void SubTest()
{
    var closeEvent = new TaskCompletionSource<bool>();

    var connection = EventStoreConnection.Create(new IPEndPoint(IPAddress.Loopback, 1113));

    await connection.ConnectAsync().ConfigureAwait(false);
    var streamName = Guid.NewGuid().ToString();

    var sub = await connection.SubscribeToStreamAsync(streamName, true, (subscription, e) => { }).ConfigureAwait(false);
    //var sub = connection.SubscribeToStreamAsync(streamName, true, (subscription, e) => { }).GetAwaiter().GetResult();

    sub.Unsubscribe();

    //Verify closed
    connection.Closed += (sender, args) =>
    {
        Console.WriteLine("Closed");
        closeEvent.SetResult(true);
    };

    connection.Close();

    if (await Task.WhenAny(closeEvent.Task, Task.Delay(5000)) == closeEvent.Task)
    {
        Console.WriteLine("Close signalled via event");
        Assert.Pass();
    }
    else
    {
        Console.WriteLine("Failed to close connection {0}", connection.ConnectionName);
        Assert.Fail(string.Format("Failed to close connection {0}", connection.ConnectionName));
    }
}
```

**Comment by SzymonPobiega** [comment] 2016-04-05 08:00
Thanks a lot @hayley-jean . That all now makes sense!

**Comment by SzymonPobiega** [comment] 2016-04-05 08:10
@gregoryyoung @pgermishuys I think it can be closed now, unless you want to provide some kind of `Task EnsureClosed()` method in the connection that actually makes sure the connection has been closed using the code @hayley-jean provided.

**Closed** 2016-04-12 09:31 UTC
Labels: bug
