### ISSUE TITLE
Support .NET Core?

### ISSUE THREAD

**Issue by thangchung** [EventStore/EventStore#1050] opened 2016-09-16 10:47 UTC
Hey guys,
I have read the awesome article at [Event Sourcing awesome](https://tech.jet.com/blog/2016/09-07-event-sourcing-awesome/), and considered to apply the EventStore for my next project using .NET Core, but I found out that it did not support .NET Core up to now. Do you guys have any plans to upgrade it to .NET Core?

**Comment by pgermishuys** [comment] 2016-09-16 10:52
Hey @thangchung, thanks for considering Event Store. We have plans to release a supported .NET Core client API, but not the Event Store server just yet. You can follow the issue here and I will close this [one](https://github.com/EventStore/EventStore/issues/757) in favour of keeping these types of discussions in a single thread/issue.

https://github.com/EventStore/EventStore/issues/757

**Closed by pgermishuys** 2016-09-16 10:52 UTC

**Comment by thangchung** [comment] 2016-09-16 10:56
@pgermishuys Thank you very much for your answer. I will have a look into the #757 :+1:

**Comment by MNF** [comment] 2017-11-07 13:08
The question was about implementing Event Store targeting .Net Core. Why it was closed as a duplicate of request for Event Store **Client** for .Net Core ?
