### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#536] opened 2015-07-06 12:47 UTC
I think we need to do a better job with error messages in particular with setting up a cluster.

Right now you can figure out what is happening but involves reading multiple logs. I can imagine some small changes to make it easier to figure out what is happening from a single log. I'm not sure all of the specific changes but I think this is something we should focus on as a goal.

**Comment by pgermishuys** [comment] 2016-06-10 07:43
It might be a good idea to include some suggestions here as to common scenarios and how best to give the user appropriate information as to what the issue is. Marking this as up for grabs.

**Closed** 2019-09-10 13:04 UTC
Labels: kind/enhancement
