### ISSUE TITLE
v5.0.9 client cannot use a loadbalanced https gossip endpoint with SNI

### ISSUE THREAD

**Issue by megakid** [EventStore/EventStore#2718] opened 2020-10-07 14:52 UTC
**Describe the bug**
Connection string of "GossipSeeds=https://my-loadbalanced-https-endpoint:443" does not work on a typical load balancer SNI setup.  Given we cannot use the discover:// protocol with HTTPS in 5.0.9 (without non-connectionstring mods?), this is the next best option but it doesn't work as the DNS name is resolved to an IP address before being a gossip GET is issued.  This prevents the loadbalancer from choosing a certificate using SNI.

**To Reproduce**
1. Expose a https loadbalanced endpoint to your ES cluster using SNI (e.g. normal NGINX behaviour)
2. Try to connect using the connectiong string "GossipSeeds=https://my-loadbalanced-https-endpoint:443"
3. See that it fails to connect as the DNS is resolved to an IP here https://github.com/EventStore/EventStore/blob/dotnet-client-v5.0.9/src/EventStore.ClientAPI/ConnectionString.cs#L60  Unfortunately the code to add a Host header is not enough to allow SNI to work.

**Expected behavior**
An HTTPS load balanced endpoint should work

**Actual behavior**
It fails to connect to the loadbalancer due to using 'https://{ip address}:443' rather than 'https://{dns}:443'

**Additional context**
I understand that this might be fixed in the latest clients so might not an issue worth fixing but thought I'd flag it up (I am trying to find a decent migration 20.6.1 path for our 5.0.9 clients).

**Comment by shaan1337** [comment] 2020-10-16 12:26
@megakid thank you. We're going to close this issue since we cannot reproduce the failure again (when targeting `netcoreapp3.1`) as you've mentioned on: https://github.com/EventStore/EventStore/pull/2720 

Please feel free to reopen the issue if you encounter it again.

**Closed by shaan1337** 2020-10-16 12:26 UTC
Labels: kind/bug
