### ISSUE TITLE
getStatePartition chrome debug on GES 3.5.0.0, wrong parameters order ? 

### ISSUE THREAD

**Issue by jrouaix** [EventStore/EventStore#845] opened 2016-03-10 14:54 UTC
Trying to create/debug a projection on a test GES we have, 

i got the event with no eventType in the partitionBy function. => ![capture1 - partitionby](https://cloud.githubusercontent.com/assets/2705498/13673166/253e6414-e6d8-11e5-91a3-e2568bf5ea26.PNG)
So i went up on the stack to find that the caller function (getStatePartition) isJson variable actually contained the eventType, but not the envelope => ![capture2 - getstatepartition](https://cloud.githubusercontent.com/assets/2705498/13673165/253d9458-e6d8-11e5-9d81-8f6af36571f5.PNG)
And then up again on the call stack got me on the get_state_partition where 
I strongly suspect some code refactoring screwed the parameters order.
![capture3 - getstatepartitioncaller](https://cloud.githubusercontent.com/assets/2705498/13673167/2541db80-e6d8-11e5-883e-424dd03366d8.PNG)

Some topic on google groups : https://groups.google.com/forum/#!topic/event-store/CXebqCE2b9w

**Comment by pgermishuys** [comment] 2016-03-10 22:30
The problem is 2 fold.

There is a mismatch between the parameters being passed between these 2 methods
https://github.com/EventStore/EventStore/blob/release-v3.6.0/src/EventStore.Projections.Core/Prelude/Projections.js#L103 and 
```
getStatePartition(event, streamId, eventType, category, sequenceNumber, metadata, linkMetadata)
```

https://github.com/EventStore/EventStore/blob/release-v3.6.0/src/EventStore.Projections.Core/Prelude/Projections.js#L319
```
getStatePartition(eventRaw, isJson, streamId, eventType, category, sequenceNumber, metadataRaw, linkMetadataRaw)
```

The other is that when debugging projections, the debugger will read the events from the server and pass them to the particular projection method. i.e. `get_state_partition`. Here the missing parameter was the `isJson`

These issues will be resolved by
https://github.com/EventStore/EventStore/pull/846 and https://github.com/EventStore/EventStore.UI/pull/119 respectively

**Closed** 2016-03-10 22:57 UTC

**Comment by gregoryyoung** [comment] 2016-03-10 22:58
This has been resolved by

https://github.com/EventStore/EventStore.UI/pull/119
and
https://github.com/EventStore/EventStore/pull/846

Both merged. I will close this issue for now.
