### ISSUE TITLE
Centralized Config handling: Add a new parameter --http-config (HttpConfig)

### ISSUE THREAD

**Issue by riccardone** [EventStore/EventStore#1660] opened 2018-06-18 10:21 UTC
Add a new parameter --http-config (HttpConfig) to EventStore that downloads a custom config from the internet (also adjust the precedence hierarchy)

**Comment by gregoryyoung** [comment] 2018-06-18 10:58
We should also define some information that we send UP to the httpconfig provider (including the ability for custom parameters)

**Comment by jageall** [comment] 2019-10-15 15:17
Closing this for now as the questions and issues that might be caused by trying to secure a remote config and troubleshooting what happens when it is not available are fairly broad

**Closed by jageall** 2019-10-15 15:17 UTC
Labels: detectability/easy, impact/low, kind/enhancement, subsystem/Core Database
