### ISSUE TITLE
Projections - Unresponsive till restart

### ISSUE THREAD

**Issue by mmuller99** [EventStore/EventStore#1056] opened 2016-09-26 13:27 UTC
We have an event store instance running in a single cluster environment handling +- a million events per day. We are reliant on the `$by_category` and `$by_event_type` system projections.

We are experiencing frequent drops in the projections in which the projections become unresponsive. At which stage we have to restart event store and the projections will catchup. The drops are occurring almost at a daily interval.

Attached are the error logs for 2016-09-23 and 2016-09-26.

[Logs.zip](https://github.com/EventStore/EventStore/files/493183/Logs.zip)

**Comment by pgermishuys** [comment] 2016-09-26 13:28
Thanks for raising this issue @mmuller99. Will take a look at the logs now.

**Comment by pgermishuys** [comment] 2016-09-26 13:32
@mmuller99 the normal (non `-err`) logs appear to be missing which will show other information which is useful for identifying possible causes. Can you possibly attach those logs please?

Thanks!

**Comment by mmuller99** [comment] 2016-09-26 13:41
Here is the log for 2016-09-26. It's quite big.

[2016-09-26-192.168.50.21-2113-cluster-node.zip](https://github.com/EventStore/EventStore/files/493204/2016-09-26-192.168.50.21-2113-cluster-node.zip)

**Comment by pgermishuys** [comment] 2016-09-26 13:56
Which projections specifically stop responding? (It doesn't appear that they are faulted).
Are you emitting/linking to streams from your custom projections?
Are you deleting any streams?

**Comment by mmuller99** [comment] 2016-09-26 13:57
And for 2016-09-23

https://www.dropbox.com/s/lobc9cba1bo3aln/2016-09-23-192.168.50.21-2113-cluster-node.zip?dl=0

**Comment by mmuller99** [comment] 2016-09-26 14:02
At times it was specific, but as of late all of them stop responding. In one of our projection we do emit.

The common occurance is always that the projection stats do not update, thus returning the same results.

**Comment by pgermishuys** [comment] 2016-09-26 14:06
Were you running earlier versions of Event Store (prior to 3.9.1) with the same projections? Did those versions exhibit the same behaviour?

Do you delete any streams?

Has the rate of events in your system increases and thus the frequency of projections becoming unresponsive?

**Comment by mmuller99** [comment] 2016-09-26 14:09
Yes we were running earlier versions, and the same behaviour occured.

We do not delete any streams.

Our frequency of events will rise indefinitely. It does feel though that the drops have been occuring more the larger the DB becomes. Currently at 97GB

**Comment by pgermishuys** [comment] 2016-09-26 14:12
Thanks for the speedy replies...
I think requires a little more investigation and if at all possible an instant messaging type platform. 

Would you be opposed to talking over such a medium? If not, mind sending me an email to pieter at geteventstore dot com with your preferred IM platform as well as contact details?

**Comment by mmuller99** [comment] 2016-09-26 14:25
@pgermishuys sent you an email

**Comment by kstrauss** [comment] 2016-09-27 13:10
I'd like to hear what results from this as we have a similar scenario (fewer events and not as large a database).

**Comment by pgermishuys** [comment] 2016-09-27 13:14
@kstrauss i'm currently on a information gathering exercise to determine the cause of this particular issue and if you don't mind, can you answer these questions for me?
- How many custom projections do you have?
- Which projections are unresponsive?
- Do you emit from any of your projections?

**Comment by kstrauss** [comment] 2016-09-27 13:33
24 custom projections (can easily provide).
$et (and as a result everybody else) as far as I can tell.
1 does an emit

Same projections (different workload) on another server that doesn't see the behavior nearly as often (it has but only once in 2-3 months. The test server I'm referring to is pretty much every day and sometimes multiple.

**Comment by mmuller99** [comment] 2016-10-19 07:09
As a test, I have disabled the projections that emit and without them we have reached the unresponsive state within a day in production.

**Comment by samidalouche** [comment] 2016-11-17 15:06
I also reported the following bug, which looks to be similar to this one: https://github.com/EventStore/EventStore/issues/1097

**Comment by hazevich** [comment] 2016-11-18 16:02
We're also encountered similar issue with system projection $streams. Dashboard tells everythings is fine, but it doesn't publish any new events for newly created streams.

**Comment by pgermishuys** [comment] 2017-01-04 09:38
Fixed by #1139

**Closed by pgermishuys** 2017-01-04 09:38 UTC
Labels: projections
