### ISSUE TITLE
System.OutOfMemoryException: Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by justenwalker** [EventStore/EventStore#1525] opened 2017-12-19 04:16 UTC
We've encountered this error which apparently happens when trying to merge PTables.
It causes an OutOfMemory Exception and crashes the node. This affects all nodes in the cluster so results in complete cluster unavailability.

Eventstore Version: 4.0.2.2
Platform: Windows Server 2012 R2
.NET Runtime: .NET Framework 4.6.1

```
[PID:12964:121 2017.12.19 01:09:33.864 FATAL GLOBAL-LOGGER       ] Global Unhandled Exception occurred.
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at EventStore.Core.Index.PTable.EnumerableTable.ReadUntilDifferentHash(Byte version, IEnumerator`1 ptableEnumerator, Func`3 upgradeHash, Func`2 existsAt, Func`2 readRecord) in C:\projects\eventstore-commercialha\oss\src\EventStore.Core\Index\PTableConstruction.cs:line 354
   at EventStore.Core.Index.PTable.EnumerableTable.MoveNext() in C:\projects\eventstore-commercialha\oss\src\EventStore.Core\Index\PTableConstruction.cs:line 336
   at EventStore.Core.Index.PTable.MergeTo2(IList`1 tables, Int64 fileSize, Int32 indexEntrySize, String outputFile, Func`3 upgradeHash, Func`2 existsAt, Func`2 readRecord, Byte version, Int32 cacheDepth) in C:\projects\eventstore-commercialha\oss\src\EventStore.Core\Index\PTableConstruction.cs:line 189
   at EventStore.Core.Index.PTable.MergeTo(IList`1 tables, String outputFile, Func`3 upgradeHash, Func`2 existsAt, Func`2 readRecord, Byte version, Int32 cacheDepth) in C:\projects\eventstore-commercialha\oss\src\EventStore.Core\Index\PTableConstruction.cs:line 135
   at EventStore.Core.Index.IndexMap.AddPTable(PTable tableToAdd, Int64 prepareCheckpoint, Int64 commitCheckpoint, Func`3 upgradeHash, Func`2 existsAt, Func`2 recordExistsAt, IIndexFilenameProvider filenameProvider, Byte version, Int32 indexCacheDepth) in C:\projects\eventstore-commercialha\oss\src\EventStore.Core\Index\IndexMap.cs:line 337
   at EventStore.Core.Index.TableIndex.ReadOffQueue() in C:\projects\eventstore-commercialha\oss\src\EventStore.Core\Index\TableIndex.cs:line 301
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by jen20** [comment] 2017-12-19 04:19
How big are the tables you are trying to merge?

**Comment by jen20** [comment] 2017-12-19 04:25
In addition, do you have any sense for the longest streams present in this database?

**Comment by justenwalker** [comment] 2017-12-19 04:28
The largest table is 16GB.

**Comment by jen20** [comment] 2017-12-19 04:42
@justenwalker An immediate fix _should_ be to enable `gcAllowVeryLargeObjects` in the configuration for this node. Can you confirm that this is an instance which has been upgraded from older versions and thus is upgrading version 1 indices? We're investigating a better fix for this at the moment.

**Comment by jen20** [comment] 2017-12-19 04:43
If this issue is something you want an SLA on, please open a ticket via the support system rather than GitHub Issues, however!

**Comment by justenwalker** [comment] 2017-12-19 05:09
Thanks, I've set the config via `EventStore.ClusterNode.exe.config`. Won't know if it worked until the PTables are loaded (for several hours), but I'll update come back here and post an update if this resolves the issue.

**Comment by justenwalker** [comment] 2017-12-19 05:17
I see `PTables merge started (specialized for <= 2 tables).` in the previous day's logs; so I assume from this it is upgrading the index version from an older one.

**Comment by justenwalker** [comment] 2017-12-19 05:20
I see `Loading PTable (Version: 1)` in the logs; so it looks like it is loading an older version. the PTable id corresponds to two largest ones

**Comment by jen20** [comment] 2017-12-19 06:10
Yes, that confirms our suspicion of what is causing this. We should have a patch for this either in tomorrow's RC or the following one, regardless of whether the runtime configuration does the trick.

**Comment by shaan1337** [comment] 2017-12-19 12:47
@justenwalker do you have an idea of the size of the largest streams in those PTables?

The issue is occuring because all index entries for a stream are being added to memory during the upgrade from PTable V1 to sort out possible stream hash collisions.

Based on my tests, crashes occur after around 200 million entries. Are your stream lengths of that order or much less?

Even if you do use `gcAllowVeryLargeObjects enabled="true"`, you should have enough memory on the server (maybe 5-8 more gigs of RAM) to be able to handle these merges, otherwise you will run into other `Out of memory` exceptions a bit later.

We're working on a fix to prevent this from happening again by doing the sorting externally(on disk)

**Comment by justenwalker** [comment] 2017-12-19 14:30
This morning the eventstore cluster came online and hasn't crashed yet. As the workaround works as expected. Thanks, @jen20

**Comment by justenwalker** [comment] 2017-12-19 14:32
@shaan1337 our first attempt to solve the issue was to scale up the machine sizes to add additional memory; we have sufficient headroom to merge the larger PTables. I'd be happy to get more information about the stream lengths - Do you know how I can get these stats?

**Comment by jen20** [comment] 2017-12-19 14:35
:+1: @justenwalker, good news! As @shaan1337 said we're working on getting a fix out that mitigates this for very long streams - this seems to be an unfortunate side effect of the way `List<T>` manages underlying storage.

**Comment by shaan1337** [comment] 2017-12-21 06:41
@justenwalker that's good news :)

Unfortunately, there's no easy way to know the stream sizes from the EventStore. However, the size of the PTables being merged should give us an idea of its max length. 

Can you please grab this info from the logs when those 2 ptables were being merged? We're interested to know the number of entries:
`Loading PTable (Version: 1)  (xxxx entries, cache depth 16) `

**Comment by jageall** [comment] 2019-10-03 10:34
Closing due to lack of feedback since request was made

**Closed by jageall** 2019-10-03 10:34 UTC
Labels: detectability/hard, impact/high, kind/bug, subsystem/Core Database
