### ISSUE TITLE
Eventstore crash with log  "Index was outside the bounds of the array"

### ISSUE THREAD

**Issue by vietkute02** [EventStore/EventStore#3243] opened 2021-10-25 03:51 UTC
**Describe the bug**
Eventstore crash while handle projection event

**To Reproduce**
I don't know how to reproduce, it happen then restart and working normally

**Expected behavior**
Event could be handle by projection normally

**Actual behavior**
Server crash and Event process later

**Config/Logs/Screenshots**

> [    1,21,14:14:13.140,ERR] The '"events"' projection faulted due to '"Index was outside the bounds of the array.\r\n   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)\n   at EventStore.Core.Helpers.IODispatcher.ReadBackward(String streamId, Int64 fromEventNumber, Int32 maxCount, Boolean resolveLinks, ClaimsPrincipal principal, Action`1 action, Action timeoutAction, Guid corrId)\n   at EventStore.Projections.Core.Services.Processing.DefaultCheckpointManager.ReadPartitionStream(String partitionStreamName, Int64 eventNumber, CheckpointTag requestedStateCheckpointTag, Action`1 loadCompleted, String stateEventType) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/DefaultCheckpointManager.cs:line 107\n   at EventStore.Projections.Core.Services.Processing.StagedProcessingQueue.Process(Int32 max) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/StagedProcessingQueue.cs:line 101\n   at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessOneEventBatch() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjectionQueue.cs:line 127\n   at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessEvent() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjectionQueue.cs:line 51\n   at EventStore.Projections.Core.Services.Processing.EventSubscriptionBasedProjectionProcessingPhase.ProcessEvent() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EventSubscriptionBasedProjectionProcessingPhase.cs:line 132\n   at EventStore.Projections.Core.Services.Processing.CoreProjection.Tick() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjection.cs:line 542"'
[    1,21,14:14:14.027,ERR] The '"user-interactive"' projection faulted due to '"Index was outside the bounds of the array.\r\n   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)\n   at EventStore.Core.Helpers.IODispatcher.ReadBackward(String streamId, Int64 fromEventNumber, Int32 maxCount, Boolean resolveLinks, ClaimsPrincipal principal, Action`1 action, Nullable`1 corrId)\n   at EventStore.Projections.Core.Services.Processing.EmittedStream.SubmitListEvents(CheckpointTag upTo, Int64 fromEventNumber) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs:line 397\n   at EventStore.Projections.Core.Services.Processing.ProjectionCheckpoint.EmitEventsToStream(String streamId, EmittedEventEnvelope[] emittedEvents) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/ProjectionCheckpoint.cs:line 128\n   at EventStore.Projections.Core.Services.Processing.ProjectionCheckpoint.ValidateOrderAndEmitEvents(EmittedEventEnvelope[] events) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/ProjectionCheckpoint.cs:line 83\n   at EventStore.Projections.Core.Services.Processing.EventSubscriptionBasedProjectionProcessingPhase.FinalizeEventProcessing(EventProcessedResult result, CheckpointTag eventCheckpointTag, Single progress) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EventSubscriptionBasedProjectionProcessingPhase.cs:line 460\n   at EventStore.Projections.Core.Services.Processing.CommittedEventWorkItem.WriteOutput() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CommittedEventWorkItem.cs:line 69\n   at EventStore.Projections.Core.Services.Processing.StagedProcessingQueue.Process(Int32 max) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/StagedProcessingQueue.cs:line 101\n   at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessOneEventBatch() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjectionQueue.cs:line 127\n   at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessEvent() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjectionQueue.cs:line 51\n   at EventStore.Projections.Core.Services.Processing.EventSubscriptionBasedProjectionProcessingPhase.ProcessEvent() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EventSubscriptionBasedProjectionProcessingPhase.cs:line 132\n   at EventStore.Projections.Core.Services.Processing.CoreProjection.Tick() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjection.cs:line 542"'
[    1,21,14:28:57.694,INF] Resetting '"events"' projection
[    1,21,14:28:57.706,INF] '"events"' projection source has been written
[    1,21,14:28:57.736,ERR] The '"events"' projection faulted due to '"Index was outside the bounds of the array.\r\n   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)\n   at EventStore.Core.Helpers.IODispatcher.ReadBackward(String streamId, Int64 fromEventNumber, Int32 maxCount, Boolean resolveLinks, ClaimsPrincipal principal, Action`1 action, Action timeoutAction, Guid corrId)\n   at EventStore.Projections.Core.Services.Processing.DefaultCheckpointManager.ReadPartitionStream(String partitionStreamName, Int64 eventNumber, CheckpointTag requestedStateCheckpointTag, Action`1 loadCompleted, String stateEventType) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/DefaultCheckpointManager.cs:line 107\n   at EventStore.Projections.Core.Services.Processing.StagedProcessingQueue.Process(Int32 max) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/StagedProcessingQueue.cs:line 101\n   at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessOneEventBatch() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjectionQueue.cs:line 127\n   at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessEvent() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjectionQueue.cs:line 51\n   at EventStore.Projections.Core.Services.Processing.EventSubscriptionBasedProjectionProcessingPhase.ProcessEvent() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EventSubscriptionBasedProjectionProcessingPhase.cs:line 132\n   at EventStore.Projections.Core.Services.Processing.CoreProjection.Tick() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjection.cs:line 542"'
[    1,21,14:29:24.919,INF] Resetting '"user-interactive"' projection
[    1,21,14:29:24.930,INF] '"user-interactive"' projection source has been written
[    1,21,14:29:25.177,ERR] The '"user-interactive"' projection faulted due to '"Index was outside the bounds of the array.\r\n   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)\n   at EventStore.Core.Helpers.IODispatcher.ReadBackward(String streamId, Int64 fromEventNumber, Int32 maxCount, Boolean resolveLinks, ClaimsPrincipal principal, Action`1 action, Nullable`1 corrId)\n   at EventStore.Projections.Core.Services.Processing.EmittedStream.SubmitListEvents(CheckpointTag upTo, Int64 fromEventNumber) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs:line 397\n   at EventStore.Projections.Core.Services.Processing.ProjectionCheckpoint.EmitEventsToStream(String streamId, EmittedEventEnvelope[] emittedEvents) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/ProjectionCheckpoint.cs:line 128\n   at EventStore.Projections.Core.Services.Processing.ProjectionCheckpoint.ValidateOrderAndEmitEvents(EmittedEventEnvelope[] events) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/ProjectionCheckpoint.cs:line 83\n   at EventStore.Projections.Core.Services.Processing.EventSubscriptionBasedProjectionProcessingPhase.FinalizeEventProcessing(EventProcessedResult result, CheckpointTag eventCheckpointTag, Single progress) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EventSubscriptionBasedProjectionProcessingPhase.cs:line 460\n   at EventStore.Projections.Core.Services.Processing.CommittedEventWorkItem.WriteOutput() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CommittedEventWorkItem.cs:line 69\n   at EventStore.Projections.Core.Services.Processing.StagedProcessingQueue.Process(Int32 max) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/StagedProcessingQueue.cs:line 101\n   at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessOneEventBatch() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjectionQueue.cs:line 127\n   at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessEvent() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjectionQueue.cs:line 51\n   at EventStore.Projections.Core.Services.Processing.EventSubscriptionBasedProjectionProcessingPhase.ProcessEvent() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EventSubscriptionBasedProjectionProcessingPhase.cs:line 132\n   at EventStore.Projections.Core.Services.Processing.CoreProjection.Tick() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CoreProjection.cs:line 542"'
[    1,10,14:30:16.402,FTL] Global Unhandled Exception occurred.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at EventStore.Core.Helpers.IODispatcher.ReadBackward(String streamId, Int64 fromEventNumber, Int32 maxCount, Boolean resolveLinks, ClaimsPrincipal principal, Action`1 action, Nullable`1 corrId)
   at EventStore.Projections.Core.Services.Processing.EmittedStream.SubmitListEvents(CheckpointTag upTo, Int64 fromEventNumber) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs:line 397
   at EventStore.Projections.Core.Services.Processing.EmittedStream.Handle(ReadTimeout message) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs:line 424
   at EventStore.Core.Services.TimerService.ThreadBasedScheduler.DoTiming() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/TimerService/ThreadBasedScheduler.cs:line 75
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at EventStore.Core.Helpers.IODispatcher.ReadBackward(String streamId, Int64 fromEventNumber, Int32 maxCount, Boolean resolveLinks, ClaimsPrincipal principal, Action`1 action, Nullable`1 corrId)
   at EventStore.Projections.Core.Services.Processing.EmittedStream.SubmitListEvents(CheckpointTag upTo, Int64 fromEventNumber) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs:line 397
   at EventStore.Projections.Core.Services.Processing.EmittedStream.Handle(ReadTimeout message) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs:line 424
   at EventStore.Core.Services.TimerService.ThreadBasedScheduler.DoTiming() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/TimerService/ThreadBasedScheduler.cs:line 75
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**EventStore details**
 - EventStore server version: 20.10.4.0 

 - Operating system: Docker Image  eventstore/eventstore:20.10.4-bionic

 - EventStore client version (if applicable):

**Comment by megakid** [comment] 2021-11-04 15:22
We had this today (raised commercial support ticket) when upgrading v5 cluster to v21.6.

Cursory glance at the stack trace seems to indicate it is caused by unsafe threading over a `HashSet<>`.

**Comment by jageall** [comment] 2021-11-18 07:15
fixed by #3270,  #3271 and  #3272

**Closed by jageall** 2021-11-18 07:15 UTC
Labels: kind/bug, subsystem/projections
