### ISSUE TITLE
Clients connections during Server start leads to incorrect streams state afterwards

### ISSUE THREAD

**Issue by volaticus** [EventStore/EventStore#2813] opened 2021-02-10 16:01 UTC
**Describe the bug**
If GRPC clients trying to connect (e.g. Subscribe to stream) to server that is in process of startup (ReadIndex Rebuilding)  then after server startup completes  streams that were accessed by clients are broken (only part of the streams is visible). 
But actually no events gets lost, after server restart with no clients trying to connect all events in all streams become accessible.

**To Reproduce**
1. Start attempts to subscribe to "streamA"
2. Start EventStore Node
3. After EventStore started observe live position of "streamA" for connected client

**Actual behavior**
Live position of "streamA" is points not to the end of the stream, events behind wrong calculated last position is not accessible

**Expected behavior**
- Connection of clients while server is not ready should be rejected
- After successful connection client should get all events present in stream

**EventStore details**
 - EventStore server version: 20.10.0 Single Node, SelfSigned certificate
 CONFIG:                   eventstore.conf (Command Line)
        DB:                       db\Data (Config File)
        INDEX:                    db\Index (Config File)
        LOG:                      db\Logs (Config File)
        CERTIFICATE FILE:        certs\node1\node.crt (Config File)
        CERTIFICATE PRIVATE KEY FILE: certs\node1\node.key (Config File)
        TRUSTED ROOT CERTIFICATES PATH: certs\ca (Config File)
        INT IP:                   127.0.0.1 (Config File)
        EXT IP:                   127.0.0.1 (Config File)
        HTTP PORT:                2113 (Config File)
        INT TCP PORT:             1112 (Config File)
        ENABLE EXTERNAL TCP:      false (Config File)
        ENABLE ATOM PUB OVER HTTP: true (Config File)
 - Operating system: Windows 10
 - EventStore client version (if applicable): EventStore.Client.Grpc.Streams 20.10.0

**Additional context**
It seems like upon client connection Authorization logic trying to fetch EffectiveAcl which in turn requests stream metadata and incorrect StreamLastEventNumber gets cached during this process. And only after that "subscription" command is initiated and rejected with ServerNotReady error.

**Comment by dhingrak** [comment] 2023-01-19 16:30
We are unable to reproduce this issue in our environment. From our testing, we believe that the issue is fixed in version v22.10. If you are still experiencing this issue, would you please provide us with a minimal reproduction steps that we can try on our side. 

Thank you.

**Comment by hayley-jean** [comment] 2023-04-12 11:45
Hi @volaticus, we are closing this issue for now as we couldn't reproduce it on version 22.10.
Please reopen this issue if you experience it again on a later version

**Closed by hayley-jean** 2023-04-12 11:45 UTC
Labels: kind/bug, action/investigate, action/close if no further feedback, backport
