### ISSUE TITLE
Why to not run eventstore in Container?

### ISSUE THREAD

**Issue by Gentlehag** [EventStore/EventStore#1251] opened 2017-03-21 11:29 UTC
on docker hub I found that there is a docker image for eventstore https://hub.docker.com/r/eventstore/eventstore/

but there is a annotation that this is only for development . Is there a reason why we should not use docker container to run eventstore?

**Comment by gregoryyoung** [comment] 2017-03-21 11:31
Running databases in general is a sketchy idea. You can do it but there is a ton of complications that come with it + performance loss. Its YALC (yet another layer of complexity)

**Comment by pgermishuys** [comment] 2017-03-23 15:05
Duplicate of https://github.com/EventStore/eventstore-docker/issues/28

**Closed by pgermishuys** 2017-03-23 15:05 UTC
Labels: question
