### ISSUE TITLE
Create Custom Projections in Embedded GES - without an HTTP endpoint

### ISSUE THREAD

**Issue by kstrauss** [EventStore/EventStore#1347] opened 2017-07-03 14:04 UTC
I'd like to use the embedded GES more, so I don't have to worry about ports with my integration tests. A sticking point I believe is being to create custom projections without exposing an Http Listener. Right now we use a pool of ports for which acls have been preallocated on.

One thought would be for ProjectionsManager to be able to be used with a ClusterVNode ala the EmbeddedEventStoreConnection.Create method.

Any suggestions?

**Comment by jageall** [comment] 2019-10-02 07:56
There was an issue raised about being able to allow projections to be created from files rather than through the http api which could help with this. Currently having trouble finding it though...

**Comment by oskardudycz** [comment] 2021-12-13 09:10
Once we decide whether we'll make Embedded ESDB again, this should be included. I'm closing this as duplicate of https://github.com/EventStore/EventStore/issues/1957

**Closed by oskardudycz** 2021-12-13 09:10 UTC
Labels: kind/enhancement, subsystem/projections, action/investigate
