### ISSUE TITLE
Problem with Time difference in docker 3 node cluster

### ISSUE THREAD

**Issue by bhugot** [EventStore/EventStore#1641] opened 2018-05-25 11:41 UTC
Hello,

I tryed the docker example for cluster (https://github.com/EventStore/eventstore-docker#cluster-mode)

And after a few minutes I got the following error:

> [00001,17,11:29:29.760] SLOW QUEUE MSG [MonitoringQueue]: GetFreshStats - 683ms. Q: 0/0.
[00001,12,11:29:30.620] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:29:30.620, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:29:39.666] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:29:39.666, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:29:42.662] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:29:42.662, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:29:47.696] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:29:47.696, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:29:51.719] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:29:51.719, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:29:53.730] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:29:53.730, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:29:57.753] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:29:57.753, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,20,11:30:00.650] SLOW QUEUE MSG [MonitoringQueue]: GetFreshStats - 759ms. Q: 0/0.
[00001,12,11:30:02.777] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:30:02.777, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:30:13.852] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:30:13.852, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:30:15.861] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:30:15.861, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:30:16.865] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:30:16.865, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:30:18.871] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:30:18.871, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:30:20.887] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:30:20.887, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:30:21.891] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:30:21.891, peer's time stamp: 2018-05-25 11:19:12.418.
[00001,12,11:30:24.902] Time difference between us and [10.0.0.3:2112] is too great! UTC now: 2018-05-25 11:30:24.902, peer's time stamp: 2018-05-25 11:19:12.418.

Any idea on this?

**Comment by gregoryyoung** [comment] 2018-05-25 12:31
How are you setting time on your nodes? Its complaining the difference in tine between the nodes is too great.

**Comment by bhugot** [comment] 2018-05-25 12:32
I just used the example nothing specifique. But look at the peer's time stamp, it's never increased

**Comment by mat-mcloughlin** [comment] 2019-10-09 08:10
This is expected behaviour and just needs documenting

**Comment by DanGardnerr** [comment] 2020-07-20 09:57
@mat-mcloughlin Sorry to comment on quite an old thread but I can't see any resolution to the docs around the issue. 

I'm having the same issue problem where I'm receiving a timeout between peers, but the peers timestamp in the log is always the same.

Could you elaborate on why this behaviour is expected please?

**Comment by jen20** [comment] 2020-07-20 15:48
@DanGardnerr What version are you using?

**Comment by DanGardnerr** [comment] 2020-07-20 16:01
@jen20 Version 5.0.8

I should also probably add that we're running each node within a separate docker container - not sure if this will have any bearing!

**Comment by jen20** [comment] 2020-07-20 16:46
It shouldn't matter (if they are on the same host) - Linux only got a time namespace in kernel 5.6 and it's unlikely that's made it to any mainstream distributions.

Can you try this with version 20.6 instead? We're not supporting v5 any more except for commercial customers (and even then, not in Docker). 20.6 has a wide variety of improvements including new client access protocols, being based on Core CLR instead of Mono, and a supported Docker image.

I'll go ahead and close this issue out since it's for an unsupported version, but if you experience this with 20.6 feel free to open a new one with logs, topology and configuration.

**Closed by jen20** 2020-07-20 16:46 UTC
Labels: area/documentation
