### ISSUE TITLE
Indempotency not working on event copy to other stream

### ISSUE THREAD

**Issue by Kleiboy92** [EventStore/EventStore#387] opened 2015-01-30 10:31 UTC
When event with same ID is copied to another stream the indepontency check is not working there.

to reproduce

```
curl -i -d "{}" "http://127.0.0.1:2113/streams/test" -H "Content-Type:application/json" -H "ES-EventType:TestType" -H "ES-EventId:9daa189c-356b-4ce8-9f4b-cbb3a277d6a3"
curl -i -d "{}" "http://127.0.0.1:2113/streams/test" -H "Content-Type:application/json" -H "ES-EventType:TestType" -H "ES-EventId:9daa189c-356b-4ce8-9f4b-cbb3a277d6a3"
curl -i -d "{}" "http://127.0.0.1:2113/streams/testt" -H "Content-Type:application/json" -H "ES-EventType:TestType" -H "ES-EventId:9daa189c-356b-4ce8-9f4b-cbb3a277d6a3"
curl -i -d "{}" "http://127.0.0.1:2113/streams/testt" -H "Content-Type:application/json" -H "ES-EventType:TestType" -H "ES-EventId:9daa189c-356b-4ce8-9f4b-cbb3a277d6a3"
```

The result is one event in **test** stream and two events in **testt** stream.

**Comment by jen20** [comment] 2015-01-30 15:12
I can reproduce this. Although idempotency without an expected version is a "best efforts" type thing in this case it seems intuitive that it should work. We'll investigate.

**Comment by gregoryyoung** [comment] 2015-04-16 10:19
@jen20 The idempotency check IIRC associates an event id to a stream and doesn't support multiple

@Kleiboy92 you should not have two events in the system with the same id, this can lead to weird behaviour with things like idempotency checks. When "copying the events" they actually have a new id in the second stream as they are different events. We will probably fix this but having multiple things with the same "unique id" is in general probably a bad idea. This id is also internal for us (you can always use your own id as well if you want a non-unique id)

**Comment by pgermishuys** [comment] 2016-06-10 08:01
@gregoryyoung are you still of the opinion that we should "fix" this?

**Comment by gregoryyoung** [comment] 2016-06-10 08:06
@pgermishuys it seems to confuse people. Checking the stream as well as the id would likely remove confusion for a lot of people

**Comment by pgermishuys** [comment] 2017-04-04 10:53
There is another issue which is a duplicate of this one, closing this one in favour of the other where a more detailed discussion has taken place. 

https://github.com/EventStore/EventStore/issues/1173

**Closed by pgermishuys** 2017-04-04 10:53 UTC
Labels: investigate
